#!/usr/bin/env python3
"""Ensure investigator member guardian-claw on the operator's iN2N risk (067 T054).

Idempotent:
  - Never renames or deletes an existing risk
  - Never wipes member .env / secrets on re-run
  - If guardian-claw (or another network-guardian-profile investigator) exists → OK
  - If missing and this claw is Border → provision member + staging scaffold

Usage:
  python3 scripts/ensure-guardian-claw.py
  python3 scripts/ensure-guardian-claw.py --json
  python3 scripts/ensure-guardian-claw.py --member-name guardian-claw --dry-run

Exit codes: 0 ok / ensured, 1 error, 2 risk not border / mesh not ready (skip)
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PROTO = REPO / "mcp-servers" / "protocol-mcp"
sys.path.insert(0, str(PROTO))

MEMBER_DEFAULT = "guardian-claw"
PROFILE = "network-guardian"


def _load_env(path: Path) -> dict:
    out = {}
    try:
        for line in path.read_text().splitlines():
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            k, v = s.split("=", 1)
            out[k.strip()] = v.strip().strip('"').strip("'")
    except OSError:
        pass
    return out


def _scope_names(scope_raw) -> set:
    names = set()
    if not scope_raw:
        return names
    try:
        data = json.loads(scope_raw) if isinstance(scope_raw, str) else scope_raw
    except (TypeError, ValueError):
        return names
    for e in data or []:
        if isinstance(e, dict) and e.get("name"):
            names.add(e["name"])
        elif isinstance(e, str):
            names.add(e)
    return names


def find_investigator(members: list) -> dict | None:
    """Prefer guardian-claw name; else network-guardian profile; else skill match."""
    by_name = None
    by_profile = None
    by_skills = None
    for m in members:
        mid = m.get("member_id") or ""
        name = m.get("display_name") or mid.split("/")[-1]
        if name == MEMBER_DEFAULT or mid.endswith(f"/{MEMBER_DEFAULT}"):
            by_name = m
        if m.get("profile") in (PROFILE, "guardian-claw"):
            by_profile = by_profile or m
        skills = _scope_names(m.get("scope"))
        if "alert-triage" in skills and "wifi-diagnosis" in skills:
            by_skills = by_skills or m
    return by_name or by_profile or by_skills


def _write_staging_if_missing(
    risk_name: str,
    member_name: str,
    enrollment_token: str | None,
    border_endpoint: str,
    env_border: dict,
) -> Path:
    """Create migration-staging/members/<name>/.env + run.sh only if absent."""
    mdir = REPO / "migration-staging" / "members" / member_name
    mdir.mkdir(parents=True, exist_ok=True)
    env_path = mdir / ".env"
    run_path = mdir / "run.sh"
    member_id = f"{risk_name}/{member_name}"
    home_scoped = Path.home() / f".openclaw-{risk_name}-{member_name}"

    if not env_path.exists():
        # Least-privilege slice: OBS + home API + model keys from Border when present
        keys = [
            "PROMETHEUS_URL",
            "LOKI_URL",
            "VICTORIAMETRICS_URL",
            "GRAFANA_URL",
            "GRAFANA_SERVICE_ACCOUNT_TOKEN",
            "ALERTMANAGER_URL",
            "UNIFI_HOST",
            "UNIFI_API_KEY",
            "HOME_API_URL",
            "HOME_API_TOKEN",
            "NETWORK_GUARDIAN_URL",
            "NETWORK_GUARDIAN_TOKEN",
            "OLLAMA_BASE_URL",
            "OLLAMA_API_KEY",
            "N2N_MEMBER_MODEL",
            "DISCORD_ALERT_CHANNEL_ID",
            "DISCORD_CHANNEL_ID",
            "DISCORD_WEBHOOK_URL",
            "ALERT_RECEIVER_URL",
            "MEMORY_DATA_DIR",
            "NETCLAW_DIR",
            "RAG_DATA_DIR",
            "RAG_EMBEDDING_MODEL",
            "RAG_RERANK_ENABLED",
            "RAG_MCP_SCRIPT",
        ]
        lines = [
            f"# Generated by ensure-guardian-claw.py for {member_id}",
            f"# Edit secrets as needed; re-runs will NOT overwrite this file.",
            "",
            "N2N_ROLE=member",
            f"N2N_RISK_NAME={risk_name}",
            f"N2N_MEMBER_ID={member_id}",
            f"N2N_BORDER_ENDPOINT={border_endpoint}",
            "N2N_MEMBER_SCOPE="
            '["n2n-member-runtime","self-status","memory","gait-session-tracking",'
            '"humanrail-escalation","wifi-diagnosis","alert-triage",'
            '"monitoring-onboard","isp-sla-claim"]',
            f"OPENCLAW_STATE_DIR={home_scoped}",
            f"OPENCLAW_CONFIG_PATH={home_scoped}/openclaw.json",
            f"NETCLAW_DIR={REPO}",
        ]
        if enrollment_token:
            lines.append(f"N2N_ENROLLMENT_TOKEN={enrollment_token}")
        else:
            lines.append("# N2N_ENROLLMENT_TOKEN=<from netclaw risk add if re-enrolling>")
        for k in keys:
            if k in env_border and env_border[k]:
                lines.append(f"{k}={env_border[k]}")
        if "N2N_MEMBER_MODEL" not in env_border:
            lines.append("N2N_MEMBER_MODEL=claude-sonnet-5")
        if "PROMETHEUS_URL" not in env_border:
            lines.append("PROMETHEUS_URL=http://127.0.0.1:9090")
        if "MEMORY_DATA_DIR" not in env_border:
            lines.append(f"MEMORY_DATA_DIR={Path.home()}/.openclaw/memory")
        # Share Border HUD knowledge corpus (vendor PDFs, etc.)
        if "RAG_DATA_DIR" not in env_border:
            lines.append(f"RAG_DATA_DIR={Path.home()}/.openclaw/rag")
        env_path.write_text("\n".join(lines) + "\n")
        os.chmod(env_path, 0o600)

    if not run_path.exists():
        run_path.write_text(
            "#!/usr/bin/env bash\n"
            "# Robust: the launcher parses the .env itself.\n"
            'export N2N_MEMBER_ENV_FILE="$(dirname "$0")/.env"\n'
            f'exec python3 "{REPO}/scripts/in2n-member.py" --idle-exit 0\n'
        )
        os.chmod(run_path, 0o755)

    return mdir


def main() -> int:
    ap = argparse.ArgumentParser(description="Ensure guardian-claw investigator member")
    ap.add_argument("--member-name", default=MEMBER_DEFAULT)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument(
        "--create-border-if-missing",
        action="store_true",
        help="If standalone and N2N_RISK_NAME set, promote to border (greenfield only)",
    )
    args = ap.parse_args()

    result = {
        "risk": None,
        "role": None,
        "investigator": None,
        "action": "none",
        "ok": False,
        "message": "",
    }

    try:
        from bgp.federation.manager import FederationManager
        from bgp.federation.risk import RiskManager
    except Exception as e:
        result["message"] = f"cannot import RiskManager: {e}"
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            print(f"ERROR: {result['message']}", file=sys.stderr)
        return 1

    border_env = _load_env(Path.home() / ".openclaw" / ".env")
    m = FederationManager()
    rm = RiskManager(m)
    risk = rm.get_risk()
    result["risk"] = risk.get("risk_name")
    result["role"] = risk.get("role")

    # Greenfield: optional promote standalone → border when risk name is known
    if (
        args.create_border_if_missing
        and rm.is_standalone()
        and (border_env.get("N2N_RISK_NAME") or os.environ.get("N2N_RISK_NAME"))
    ):
        rname = border_env.get("N2N_RISK_NAME") or os.environ.get("N2N_RISK_NAME")
        if not args.dry_run:
            rm.set_role(
                "border",
                risk_name=rname,
                enabled_stacks=border_env.get("N2N_ENABLED_STACKS") or "both",
                border_endpoint=border_env.get("N2N_BORDER_ENDPOINT")
                or "127.0.0.1:11790",
            )
            risk = rm.get_risk()
            result["risk"] = risk.get("risk_name")
            result["role"] = risk.get("role")
            result["action"] = "promoted_border"
        else:
            result["action"] = "would_promote_border"
            result["message"] = f"would set_role border risk={rname}"
            result["ok"] = True
            m.close()
            _emit(args, result)
            return 0

    if not rm.is_border():
        result["message"] = (
            f"claw role is {risk.get('role')!r} (not border); "
            "skipping member ensure — set N2N_ROLE=border and N2N_RISK_NAME, or run on Border"
        )
        result["ok"] = True  # not a hard failure for setup on member/standalone
        m.close()
        _emit(args, result)
        return 2

    risk_name = risk.get("risk_name") or border_env.get("N2N_RISK_NAME") or "home-risk"
    result["risk"] = risk_name

    members = rm.list_members()
    inv = find_investigator(members)
    if inv:
        result["investigator"] = inv.get("member_id")
        result["action"] = "exists"
        result["ok"] = True
        result["message"] = f"investigator already present: {inv.get('member_id')} (profile={inv.get('profile')}, state={inv.get('state')})"
        m.close()
        _emit(args, result)
        return 0

    # Provision new guardian-claw
    border_endpoint = (
        risk.get("border_endpoint")
        or border_env.get("N2N_BORDER_ENDPOINT")
        or "127.0.0.1:11790"
    )
    launch_cmd = (
        f'/usr/bin/bash {REPO}/migration-staging/members/{args.member_name}/run.sh'
    )

    if args.dry_run:
        result["action"] = "would_add"
        result["investigator"] = f"{risk_name}/{args.member_name}"
        result["ok"] = True
        result["message"] = f"would add_member name={args.member_name} profile={PROFILE}"
        m.close()
        _emit(args, result)
        return 0

    # Resolve specialty skills via in2n-profiles
    specialty = None
    try:
        import importlib.util

        spec = importlib.util.spec_from_file_location(
            "in2n_profiles", REPO / "scripts" / "in2n-profiles.py"
        )
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        meta = mod.PROFILE_MATCHERS.get(PROFILE, {})
        exact = meta.get("exact") or []
        specialty = [{"name": s, "type": "skill", "tier": "specialty"} for s in exact]
    except Exception:
        specialty = [
            {"name": "wifi-diagnosis", "type": "skill", "tier": "specialty"},
            {"name": "alert-triage", "type": "skill", "tier": "specialty"},
            {"name": "monitoring-onboard", "type": "skill", "tier": "specialty"},
            {"name": "isp-sla-claim", "type": "skill", "tier": "specialty"},
        ]

    try:
        out = rm.add_member(
            args.member_name,
            profile=PROFILE,
            specialty=specialty,
            launch_cmd=launch_cmd,
            on_demand=False,
        )
    except ValueError as e:
        # Race / already exists
        if "already exists" in str(e).lower():
            members = rm.list_members()
            inv = find_investigator(members)
            result["investigator"] = (inv or {}).get("member_id")
            result["action"] = "exists"
            result["ok"] = True
            result["message"] = str(e)
            m.close()
            _emit(args, result)
            return 0
        result["message"] = str(e)
        m.close()
        _emit(args, result)
        return 1

    token = out.get("enrollment_token")
    mdir = _write_staging_if_missing(
        risk_name, args.member_name, token, border_endpoint, border_env
    )

    # Scoped OpenClaw home (idempotent if already present)
    try:
        import subprocess

        subprocess.run(
            [
                sys.executable,
                str(REPO / "scripts" / "in2n-member-home.py"),
                "--risk",
                risk_name,
                "--member",
                args.member_name,
            ],
            check=False,
            cwd=str(REPO),
            capture_output=True,
            text=True,
        )
    except Exception:
        pass

    result["investigator"] = out.get("member_id")
    result["action"] = "added"
    result["ok"] = True
    result["message"] = (
        f"provisioned {out.get('member_id')}; staging={mdir}; "
        f"start with: systemctl --user start netclaw-member-{risk_name}-{args.member_name} "
        f"(after: python3 scripts/in2n-services.py generate && enable)"
    )
    result["enrollment_token_set"] = bool(token)
    m.close()
    _emit(args, result)
    return 0


def _emit(args, result: dict) -> None:
    if args.json:
        print(json.dumps(result, indent=2))
        return
    print(f"risk={result.get('risk') or '-'}")
    print(f"role={result.get('role') or '-'}")
    print(f"investigator={result.get('investigator') or '-'}")
    print(f"action={result.get('action')}")
    if result.get("message"):
        print(result["message"])


if __name__ == "__main__":
    raise SystemExit(main())
