#!/usr/bin/env bash
# Show / seed Convergence investigation policy (080 Phase 9).
# Usage:
#   ./scripts/netclaw-investigation-policy.sh show
#   ./scripts/netclaw-investigation-policy.sh seed-observe-only
#   ./scripts/netclaw-investigation-policy.sh seed-investigate-critical
#   ./scripts/netclaw-investigation-policy.sh thin-agent   # show/apply T106 alert agent profile
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
POLICY="${INVESTIGATION_POLICY_PATH:-$HOME/.openclaw/investigation-policy.yaml}"
EXAMPLE="$ROOT/deploy/convergence/config/investigation-policy.example.yaml"
RECEIVER="${INVESTIGATION_POLICY_STATUS_URL:-http://127.0.0.1:8099/policy/status}"
THIN="$ROOT/scripts/netclaw-alert-agent-profile.sh"

cmd="${1:-show}"

seed_observe() {
  mkdir -p "$(dirname "$POLICY")"
  if [[ ! -f "$EXAMPLE" ]]; then
    echo "Example not found: $EXAMPLE" >&2
    exit 1
  fi
  cp "$EXAMPLE" "$POLICY"
  echo "Seeded $POLICY (default_tier: T0, empty allow_t2)"
  echo "Reload is automatic within ~30s (cache TTL) or restart netclaw-alert-receiver"
  echo "Tip: also run $THIN apply so T2 hooks use the thin agent profile"
}

seed_investigate_critical() {
  # Nuclear default_tier T0 + open only low-cardinality critical names for T2.
  # Requires thin alert agent (T106) for affordable multi-tool runs.
  mkdir -p "$(dirname "$POLICY")"
  cat >"$POLICY" <<'YAML'
# Convergence investigation policy — investigate-critical preset
# Generated by scripts/netclaw-investigation-policy.sh seed-investigate-critical
version: 1
default_tier: T0

tiers:
  T0:
    llm: none
  T1:
    llm: summarize
    max_tools: 0
    max_completion_tokens: 4000
  T2:
    llm: investigate
    agent: alert
    max_turns: 8
    max_tokens: 200000

# Low-cardinality critical only — open more as hygiene improves
allow_t2:
  - alertname: WanHardDown
  - alertname: SwitchLinkLost
    severity: critical
  - alertname: DeviceSnmpExporterDown

allow_t1: []

force_t0:
  - alertname: SwitchIdlePortsPresent
  - alertname: SwitchInterfaceDown
  - alertname: NetclawAgentMetricsDown
  - label: investigate=false

budgets:
  max_t2_per_hour: 3
  max_concurrent_t2: 2
  dedup_ttl_seconds: 1800

degrade:
  force_max_tier: null
YAML
  echo "Seeded $POLICY (observe-by-default + allow_t2 for WanHardDown / SwitchLinkLost / DeviceSnmpExporterDown)"
  echo "Ensure thin agent: $THIN apply"
  echo "Reload within ~30s or restart netclaw-alert-receiver"
}

case "$cmd" in
  show)
    echo "Policy file: $POLICY"
    if [[ -f "$POLICY" ]]; then
      echo "---"
      cat "$POLICY"
    else
      echo "(missing — alert-receiver fail-safes to T0)"
    fi
    echo "---"
    if curl -sf -m 3 "$RECEIVER" >/dev/null 2>&1; then
      curl -sS -m 3 "$RECEIVER" | python3 -m json.tool 2>/dev/null || curl -sS -m 3 "$RECEIVER"
    else
      echo "alert-receiver /policy/status not reachable at $RECEIVER"
    fi
    if [[ -x "$THIN" ]]; then
      echo "--- thin T2 agent ---"
      "$THIN" show 2>/dev/null || true
    fi
    ;;
  seed-observe-only|seed)
    seed_observe
    ;;
  seed-investigate-critical|investigate-critical)
    seed_investigate_critical
    ;;
  thin-agent|alert-agent)
    exec "$THIN" "${2:-show}"
    ;;
  *)
    echo "Usage: $0 {show|seed-observe-only|seed-investigate-critical|thin-agent}" >&2
    exit 2
    ;;
esac
