#!/usr/bin/env python3
"""Render Convergence device telemetry artifacts (Phase 10).

From convergence.yaml (or targets YAML) produce:
  - Prometheus scrape job fragment (job device_snmp, managed-section ready)
  - snmp_exporter config (auths + vendor modules with ifDescr/ifName lookups)
  - Device-side SNMP/syslog config checklist (markdown)

Usage:
  python3 scripts/render-convergence-telemetry.py \\
    --config config/convergence.example.yaml \\
    --out-scrape /tmp/device_snmp_scrape.yml \\
    --out-snmp deploy/convergence/adapters/device-snmp/snmp.yml \\
    --out-checklist /tmp/device-config-checklist.md

  python3 scripts/render-convergence-telemetry.py \\
    --targets deploy/convergence/adapters/device-snmp/targets.example.yml \\
    --out-scrape -
"""

from __future__ import annotations

import argparse
import os
import socket
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODULES_DIR = (
    REPO_ROOT / "deploy/convergence/adapters/device-snmp/modules"
)
VALID_TEMPLATES = ("cisco", "pfsense", "generic")
ROLE_DEFAULT = "switch"
MARKER_BEGIN = "# BEGIN netclaw-convergence-device-snmp"
MARKER_END = "# END netclaw-convergence-device-snmp"


def load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def normalize_template(vendor: str | None, template: str | None) -> str:
    t = (template or vendor or "generic").strip().lower()
    if t in ("ios", "ios-xe", "catalyst", "nxos"):
        return "cisco"
    if t in ("pf", "pfsense-fw", "firewall-pfsense"):
        return "pfsense"
    if t not in VALID_TEMPLATES and t != "if_mib":
        return "generic"
    if t == "if_mib":
        return "generic"
    return t


def normalize_target(raw: dict) -> dict | None:
    ip = (raw.get("ip") or raw.get("address") or "").strip()
    if not ip:
        return None
    name = (raw.get("name") or ip).strip()
    role = (raw.get("role") or ROLE_DEFAULT).strip().lower()
    vendor = (raw.get("vendor") or "").strip().lower() or None
    template = normalize_template(vendor, raw.get("template"))
    if not vendor:
        vendor = template
    return {
        "name": name,
        "ip": ip,
        "role": role,
        "vendor": vendor,
        "template": template,
    }


def targets_from_convergence(cfg: dict) -> list[dict]:
    dt = (cfg.get("device_telemetry") or {}).get("snmp") or {}
    # Include targets even when enabled=false so dry-render still works;
    # apply decides whether to enable the profile.
    out: list[dict] = []
    for t in dt.get("targets") or []:
        n = normalize_target(t)
        if n:
            out.append(n)
    return out


def targets_from_file(doc: dict) -> list[dict]:
    out: list[dict] = []
    for t in doc.get("targets") or []:
        n = normalize_target(t)
        if n:
            out.append(n)
    return out


def sort_targets(targets: list[dict]) -> list[dict]:
    return sorted(targets, key=lambda t: (t["name"].lower(), t["ip"]))


def render_scrape(
    targets: list[dict],
    *,
    site: str = "home",
    exporter: str = "snmp-device-exporter:9116",
    poll_interval: str = "60s",
    with_markers: bool = True,
) -> str:
    """Render device_snmp job. Module per target via snmp_module label + relabel."""
    lines: list[str] = []
    if with_markers:
        lines.append(MARKER_BEGIN)
    lines.extend(
        [
            "  # Generated by scripts/render-convergence-telemetry.py — Phase 10",
            "  - job_name: device_snmp",
            f"    scrape_interval: {poll_interval}",
            "    metrics_path: /snmp",
            "    params:",
            "      module: [generic]",
            "      auth: [public_v2]",
            "    static_configs:",
        ]
    )
    if not targets:
        lines.append(
            "      []  # no targets — set device_telemetry.snmp.targets in convergence.yaml"
        )
    for t in targets:
        lines.append(f'      - targets: ["{t["ip"]}"]')
        lines.append("        labels:")
        lines.append(f"          site: {site}")
        lines.append(f"          device_name: {t['name']}")
        lines.append(f"          role: {t['role']}")
        lines.append(f"          vendor: {t['vendor']}")
        lines.append(f"          snmp_module: {t['template']}")
    lines.extend(
        [
            "    relabel_configs:",
            "      - source_labels: [__address__]",
            "        target_label: __param_target",
            "      - source_labels: [__param_target]",
            "        target_label: instance",
            "      - source_labels: [snmp_module]",
            "        target_label: __param_module",
            "      - target_label: __address__",
            f"        replacement: {exporter}",
        ]
    )
    if with_markers:
        lines.append(MARKER_END)
    lines.append("")
    return "\n".join(lines)


def load_module_body(modules_dir: Path, template_id: str) -> dict:
    path = modules_dir / f"{template_id}.yml"
    if not path.is_file():
        # Fall back to generic
        path = modules_dir / "generic.yml"
    if not path.is_file():
        raise FileNotFoundError(f"Missing SNMP module template: {path}")
    body = load_yaml(path)
    if not isinstance(body, dict):
        raise ValueError(f"Module {path} must be a mapping (walk/metrics)")
    return body


def render_snmp_yml(
    targets: list[dict],
    *,
    modules_dir: Path,
    community: str = "public",
    include_if_mib_alias: bool = True,
) -> str:
    needed = sorted({t["template"] for t in targets} | set(VALID_TEMPLATES))
    # Always ship all three vendor modules so apply is stable; if_mib alias optional.
    modules: dict[str, dict] = {}
    for tid in VALID_TEMPLATES:
        modules[tid] = load_module_body(modules_dir, tid)
    if include_if_mib_alias:
        modules["if_mib"] = load_module_body(modules_dir, "if_mib")

    doc = {
        "auths": {
            "public_v2": {
                "community": community,
                "version": 2,
            }
        },
        "modules": modules,
    }
    header = (
        "# Generated by scripts/render-convergence-telemetry.py — Phase 10\n"
        f"# templates_in_use: {', '.join(needed) if targets else '(none)'}\n"
        "# Community from SNMP_COMMUNITY env at apply time — do not commit real secrets.\n"
        "# snmp_exporter v0.26+ auth-split; per-metric ifDescr/ifName lookups.\n\n"
    )
    body = yaml.dump(
        doc,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )
    return header + body


def detect_syslog_host() -> str:
    # Prefer primary outbound interface IP; fall back to hostname.
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except OSError:
        try:
            return socket.gethostbyname(socket.gethostname())
        except OSError:
            return "<convergence-host-ip>"


def render_checklist(
    targets: list[dict],
    *,
    site: str,
    syslog_host: str | None = None,
    syslog_port: int = 1514,
    community_env: str = "SNMP_COMMUNITY",
) -> str:
    host = syslog_host or detect_syslog_host()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Device telemetry config checklist — site `{site}`",
        "",
        f"Generated: {now}  ",
        "By: `scripts/render-convergence-telemetry.py` (Phase 10)  ",
        "",
        "Secrets stay in env — **never** commit community strings.",
        "",
        "## Convergence collector endpoints",
        "",
        f"| Item | Value |",
        f"|------|-------|",
        f"| SNMP community env | `{community_env}` (set in `deploy/convergence/.env`) |",
        f"| Syslog destination | `{host}` UDP port **{syslog_port}** |",
        f"| SNMP poller | Convergence snmp_exporter (compose profile `device-snmp`) |",
        "",
        "## Inventory targets",
        "",
        "| Name | IP | Role | Vendor | Template |",
        "|------|-----|------|--------|----------|",
    ]
    if not targets:
        lines.append("| _(none)_ | | | | |")
    for t in targets:
        lines.append(
            f"| {t['name']} | {t['ip']} | {t['role']} | {t['vendor']} | {t['template']} |"
        )
    lines.extend(
        [
            "",
            "## SNMP (read-only) — device side",
            "",
            f"Set a read-only community and put the same value in `{community_env}` on the NetClaw host.",
            "",
            "### Cisco IOS / IOS-XE",
            "",
            "```text",
            f"snmp-server community <value-from-{community_env}> RO",
            "! optional: snmp-server location ...",
            "```",
            "",
            "### pfSense",
            "",
            "1. **Services → SNMP** — enable SNMP, set read community to match "
            f"`{community_env}`.",
            "2. Ensure LAN/mgmt ACL allows the Convergence host to poll UDP/161.",
            "",
            "## Syslog — device side",
            "",
            f"Send device syslog to **{host}:{syslog_port}** (UDP) when "
            "`device_telemetry.syslog.enabled` / profile `device-syslog` is on.",
            "",
            "### Cisco",
            "",
            "```text",
            f"logging host {host} transport udp port {syslog_port}",
            "logging trap informational",
            "```",
            "",
            "### pfSense",
            "",
            f"**Status → System Logs → Settings** (or **Services → Syslog**): remote "
            f"server `{host}`, port `{syslog_port}`.",
            "",
            "## Verify (after apply)",
            "",
            "```bash",
            "./scripts/convergence-telemetry-apply.sh   # if not already applied",
            "./deploy/convergence/smoke-device-snmp.sh",
            "# Named interfaces:",
            "curl -sG 'http://127.0.0.1:9090/api/v1/query' \\",
            "  --data-urlencode 'query=count by (device_name,interface_name) (interface_status)'",
            "# Grafana: http://127.0.0.1:3300 → folder Convergence",
            "```",
            "",
            "## Full vendor MoP",
            "",
            "See `deploy/convergence/adapters/device-snmp/device-config-snippets.md` "
            "for complete Cisco / pfSense / generic steps (T131).",
            "",
            "## Non-goals (v1)",
            "",
            "- Auto-push of this config onto devices (checklist only).",
            "- Committing real community strings.",
            "",
        ]
    )
    return "\n".join(lines)


def inject_managed_section(prometheus_yml: str, scrape_block: str) -> str:
    """Replace or append managed device_snmp section in prometheus.yml text."""
    begin = MARKER_BEGIN
    end = MARKER_END
    # scrape_block already includes markers when with_markers=True
    if begin in prometheus_yml and end in prometheus_yml:
        pre, rest = prometheus_yml.split(begin, 1)
        _, post = rest.split(end, 1)
        # drop leading newline duplication
        if post.startswith("\n"):
            post = post[1:]
        return pre + scrape_block.rstrip("\n") + "\n" + post

    # No markers: try replace existing un-marked device_snmp job, else append.
    lines = prometheus_yml.splitlines(keepends=True)
    out: list[str] = []
    i = 0
    replaced = False
    while i < len(lines):
        line = lines[i]
        # Detect start of device_snmp job (possibly with preceding comments)
        if (
            not replaced
            and line.lstrip().startswith("- job_name: device_snmp")
        ):
            # Walk back comment lines that are part of the job header
            # (already emitted? keep simple: drop from this line until next job or EOF)
            # Remove trailing comments immediately above that we already wrote?
            # Pop prior comment block about device_snmp if present
            while out and (
                out[-1].lstrip().startswith("#")
                or out[-1].strip() == ""
            ):
                # only strip comments that mention device_snmp / Campus
                prev = out[-1]
                if prev.strip() == "":
                    break
                if "device_snmp" in prev or "Campus/wired" in prev or "Phase 8" in prev:
                    out.pop()
                    continue
                break
            # skip until next top-level job or end of scrape_configs-ish
            i += 1
            while i < len(lines):
                nxt = lines[i]
                if nxt.startswith("  - job_name:"):
                    break
                if nxt.startswith("scrape_configs:") or (
                    nxt and not nxt[0].isspace() and not nxt.lstrip().startswith("#")
                ):
                    break
                i += 1
            # insert managed block (ensure indentation at job level)
            block = scrape_block
            if not block.endswith("\n"):
                block += "\n"
            out.append("\n" if out and not out[-1].endswith("\n") else "")
            # strip accidental double blank
            out.append(block if block.startswith("  ") or block.startswith("#") else block)
            replaced = True
            continue
        out.append(line)
        i += 1

    if not replaced:
        # Append before end of file
        text = "".join(out).rstrip() + "\n\n" + scrape_block.rstrip() + "\n"
        return text
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Render Convergence device telemetry (Phase 10)"
    )
    ap.add_argument("--config", type=Path, help="convergence.yaml")
    ap.add_argument("--targets", type=Path, help="targets YAML (targets: [...])")
    ap.add_argument("--site", default=None, help="override site label")
    ap.add_argument(
        "--modules-dir",
        type=Path,
        default=DEFAULT_MODULES_DIR,
        help="vendor module templates directory",
    )
    ap.add_argument(
        "--exporter",
        default="snmp-device-exporter:9116",
        help="Prometheus scrape replacement for snmp_exporter",
    )
    ap.add_argument(
        "--community",
        default=os.environ.get("SNMP_COMMUNITY", "public"),
        help="SNMPv2c community for snmp.yml (default SNMP_COMMUNITY or public)",
    )
    ap.add_argument("--poll-interval", default="60s")
    ap.add_argument(
        "--out-scrape",
        type=Path,
        help="write scrape fragment (use - for stdout via --print-scrape)",
    )
    ap.add_argument(
        "--out-snmp",
        type=Path,
        help="write full snmp_exporter snmp.yml",
    )
    ap.add_argument(
        "--out-checklist",
        type=Path,
        help="write device config checklist markdown",
    )
    ap.add_argument(
        "--inject-prometheus",
        type=Path,
        help="read/write this prometheus.yml with managed section",
    )
    ap.add_argument(
        "--syslog-host",
        default=None,
        help="override syslog destination IP in checklist",
    )
    ap.add_argument(
        "--syslog-port",
        type=int,
        default=1514,
    )
    ap.add_argument(
        "--print-scrape",
        action="store_true",
        help="print scrape fragment to stdout",
    )
    ap.add_argument(
        "--no-markers",
        action="store_true",
        help="omit BEGIN/END markers in scrape fragment",
    )
    args = ap.parse_args()

    if not args.config and not args.targets:
        ap.error("need --config or --targets")

    site = args.site or "home"
    poll = args.poll_interval
    targets: list[dict] = []

    if args.targets:
        doc = load_yaml(args.targets)
        targets = targets_from_file(doc)
        if doc.get("site"):
            site = str(doc["site"])
    if args.config:
        cfg = load_yaml(args.config)
        if not args.targets:
            targets = targets_from_convergence(cfg)
        if cfg.get("site") and not args.site:
            site = str(cfg["site"])
        snmp = (cfg.get("device_telemetry") or {}).get("snmp") or {}
        if snmp.get("poll_interval") and args.poll_interval == "60s":
            poll = str(snmp["poll_interval"])
        syslog = (cfg.get("device_telemetry") or {}).get("syslog") or {}
        listen = str(syslog.get("listen") or "")
        if listen and ":" in listen and args.syslog_port == 1514:
            try:
                args.syslog_port = int(listen.rsplit(":", 1)[-1])
            except ValueError:
                pass

    targets = sort_targets(targets)
    scrape = render_scrape(
        targets,
        site=site,
        exporter=args.exporter,
        poll_interval=poll,
        with_markers=not args.no_markers,
    )

    if args.print_scrape or (args.out_scrape and str(args.out_scrape) == "-"):
        sys.stdout.write(scrape if scrape.endswith("\n") else scrape + "\n")
    elif args.out_scrape:
        args.out_scrape.parent.mkdir(parents=True, exist_ok=True)
        args.out_scrape.write_text(
            scrape if scrape.endswith("\n") else scrape + "\n", encoding="utf-8"
        )
        print(f"Wrote scrape → {args.out_scrape} ({len(targets)} targets)", file=sys.stderr)

    if args.out_snmp:
        snmp_text = render_snmp_yml(
            targets,
            modules_dir=args.modules_dir,
            community=args.community,
        )
        args.out_snmp.parent.mkdir(parents=True, exist_ok=True)
        args.out_snmp.write_text(snmp_text, encoding="utf-8")
        print(f"Wrote snmp.yml → {args.out_snmp}", file=sys.stderr)

    if args.out_checklist:
        md = render_checklist(
            targets,
            site=site,
            syslog_host=args.syslog_host,
            syslog_port=args.syslog_port,
        )
        args.out_checklist.parent.mkdir(parents=True, exist_ok=True)
        args.out_checklist.write_text(md, encoding="utf-8")
        print(f"Wrote checklist → {args.out_checklist}", file=sys.stderr)

    if args.inject_prometheus:
        src = args.inject_prometheus
        if not src.is_file():
            print(f"prometheus.yml not found: {src}", file=sys.stderr)
            return 1
        original = src.read_text(encoding="utf-8")
        updated = inject_managed_section(original, scrape)
        src.write_text(updated, encoding="utf-8")
        print(f"Injected managed device_snmp section → {src}", file=sys.stderr)

    if not any(
        [
            args.out_scrape,
            args.out_snmp,
            args.out_checklist,
            args.inject_prometheus,
            args.print_scrape,
        ]
    ):
        # Default: print scrape
        sys.stdout.write(scrape if scrape.endswith("\n") else scrape + "\n")

    print(
        f"Rendered {len(targets)} target(s) site={site} "
        f"templates={sorted({t['template'] for t in targets}) or ['(none)']}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
