#!/usr/bin/env python3
"""Render Prometheus scrape fragments for device_snmp from convergence.yaml or targets YAML.

Usage:
  python3 scripts/render-device-snmp-scrape.py \\
    --config config/convergence.example.yaml \\
    --out /tmp/device_snmp_scrape.yml

  # Or standalone targets file:
  python3 scripts/render-device-snmp-scrape.py \\
    --targets deploy/convergence/adapters/device-snmp/targets.example.yml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def load_yaml(path: Path) -> dict:
    try:
        import yaml  # type: ignore
    except ImportError:
        # Minimal loader for our simple structures (no nested complexity required)
        print("PyYAML not installed; install pyyaml or pass --targets with simple format", file=sys.stderr)
        sys.exit(1)
    return yaml.safe_load(path.read_text()) or {}


def targets_from_convergence(cfg: dict) -> list[dict]:
    dt = (cfg.get("device_telemetry") or {}).get("snmp") or {}
    if not dt.get("enabled") and not dt.get("targets"):
        return []
    out = []
    for t in dt.get("targets") or []:
        if not t.get("ip"):
            continue
        out.append(
            {
                "name": t.get("name") or t["ip"],
                "ip": t["ip"],
                "role": t.get("role") or "switch",
            }
        )
    return out


def targets_from_file(doc: dict) -> list[dict]:
    return [
        {
            "name": t.get("name") or t["ip"],
            "ip": t["ip"],
            "role": t.get("role") or "switch",
        }
        for t in (doc.get("targets") or [])
        if t.get("ip")
    ]


def render_scrape(targets: list[dict], site: str = "home", exporter: str = "snmp-device-exporter:9117") -> str:
    lines = [
        "  # Generated by scripts/render-device-snmp-scrape.py — Phase 8 device SNMP",
        "  - job_name: device_snmp",
        "    scrape_interval: 60s",
        "    metrics_path: /snmp",
        "    params:",
        "      module: [if_mib]",
        "      auth: [public_v2]",
        "    static_configs:",
    ]
    if not targets:
        lines.append("      []  # no targets — enable device_telemetry.snmp in convergence.yaml")
    for t in targets:
        lines.append(f"      - targets: [\"{t['ip']}\"]")
        lines.append("        labels:")
        lines.append(f"          site: {site}")
        lines.append(f"          device_name: {t['name']}")
        lines.append(f"          role: {t['role']}")
    lines.extend(
        [
            "    relabel_configs:",
            "      - source_labels: [__address__]",
            "        target_label: __param_target",
            "      - source_labels: [__param_target]",
            "        target_label: instance",
            "      - target_label: __address__",
            f"        replacement: {exporter}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", type=Path, help="convergence.yaml")
    ap.add_argument("--targets", type=Path, help="targets.example.yml style file")
    ap.add_argument("--site", default="home")
    ap.add_argument("--out", type=Path, help="write fragment (default stdout)")
    args = ap.parse_args()

    targets: list[dict] = []
    if args.targets:
        targets = targets_from_file(load_yaml(args.targets))
    elif args.config:
        cfg = load_yaml(args.config)
        targets = targets_from_convergence(cfg)
        if cfg.get("site"):
            args.site = str(cfg["site"])
    else:
        ap.error("need --config or --targets")

    text = render_scrape(targets, site=args.site)
    if args.out:
        args.out.write_text(text)
        print(f"Wrote {args.out} ({len(targets)} targets)", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
