#!/usr/bin/env python3
"""Render Convergence device telemetry artifacts (Phase 10).

From convergence.yaml (or targets YAML) produce:
  - Prometheus scrape job fragment (job device_snmp, managed-section ready)
  - snmp_exporter config (auths + vendor modules with ifDescr/ifName lookups)
  - Device-side SNMP/syslog config checklist (markdown)

Usage:
  python3 scripts/render-convergence-telemetry.py \\
    --config config/convergence.example.yaml \\
    --out-scrape /tmp/device_snmp_scrape.yml \\
    --out-snmp deploy/convergence/adapters/device-snmp/snmp.yml \\
    --out-checklist /tmp/device-config-checklist.md

  python3 scripts/render-convergence-telemetry.py \\
    --targets deploy/convergence/adapters/device-snmp/targets.example.yml \\
    --out-scrape -
"""

from __future__ import annotations

import argparse
import os
import socket
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODULES_DIR = (
    REPO_ROOT / "deploy/convergence/adapters/device-snmp/modules"
)
VALID_TEMPLATES = ("cisco", "pfsense", "generic")
ROLE_DEFAULT = "switch"
MARKER_BEGIN = "# BEGIN netclaw-convergence-device-snmp"
MARKER_END = "# END netclaw-convergence-device-snmp"

# OTel Collector managed sections (Phase 11 / T154). Three separate blocks because
# they live in different top-level keys of the collector config.
OTEL_MARKERS = {
    "receivers": (
        "  # BEGIN netclaw-convergence-otel-snmp-receivers",
        "  # END netclaw-convergence-otel-snmp-receivers",
    ),
    "processors": (
        "  # BEGIN netclaw-convergence-otel-snmp-processors",
        "  # END netclaw-convergence-otel-snmp-processors",
    ),
    "pipelines": (
        "    # BEGIN netclaw-convergence-otel-snmp-pipelines",
        "    # END netclaw-convergence-otel-snmp-pipelines",
    ),
    "devicemap": (
        "          # BEGIN netclaw-convergence-device-map",
        "          # END netclaw-convergence-device-map",
    ),
}

# OTel metric → OID map. Names are chosen so prometheusremotewrite emits exactly
# the metric names Convergence already uses (measured in T145): `By` + monotonic
# sum → _bytes_total, annotation units like {errors}/{state} are dropped. Changing
# a unit here silently renames a metric — see otel/snmp-receivers.md.
OTEL_IF_METRICS = [
    ("interface.octets.in", "1.3.6.1.2.1.31.1.1.1.6", "By", "sum"),
    ("interface.octets.out", "1.3.6.1.2.1.31.1.1.1.10", "By", "sum"),
    ("interface.errors.in", "1.3.6.1.2.1.2.2.1.14", "{errors}", "sum"),
    ("interface.errors.out", "1.3.6.1.2.1.2.2.1.20", "{errors}", "sum"),
    ("interface.status", "1.3.6.1.2.1.2.2.1.8", "{state}", "gauge"),
    ("interface.admin.status", "1.3.6.1.2.1.2.2.1.7", "{state}", "gauge"),
]
OID_IF_DESCR = "1.3.6.1.2.1.2.2.1.2"


def otel_receiver_key(target: dict) -> str:
    """Stable, YAML-safe receiver suffix derived from the device name."""
    safe = "".join(c if c.isalnum() else "_" for c in target["name"].lower())
    return safe.strip("_") or target["ip"].replace(".", "_")


def render_otel_receivers(
    targets: list[dict],
    *,
    poll_interval: str = "60s",
    community_env: str = "SNMP_COMMUNITY",
    with_markers: bool = True,
) -> str:
    begin, end = OTEL_MARKERS["receivers"]
    out: list[str] = []
    if with_markers:
        out.append(begin)
        out.append("  # Generated by scripts/render-convergence-telemetry.py — do not hand-edit.")
        out.append("  # Edit inventory in convergence.yaml, then re-run the apply script.")
    for i, tgt in enumerate(targets):
        key = otel_receiver_key(tgt)
        out.append(f"  snmp/{key}:")
        out.append(f"    collection_interval: {poll_interval}")
        # Stagger starts so N devices are not polled in the same instant.
        out.append(f"    initial_delay: {i * 5}s")
        out.append(f"    endpoint: udp://{tgt['ip']}:161")
        out.append("    version: v2c")
        out.append(f"    community: ${{env:{community_env}}}")
        out.append("    timeout: 30s")
        out.append("    resource_attributes:")
        out.append("      interface.name:")
        out.append(f"        oid: {OID_IF_DESCR}")
        out.append("    metrics:")
        for name, oid, unit, kind in OTEL_IF_METRICS:
            if name == "interface.admin.status":
                out.append("      # ifAdminStatus — with interface.status this separates")
                out.append("      # administratively-shut from link-failed.")
            out.append(f"      {name}:")
            out.append(f'        unit: "{unit}"' if unit.startswith("{") else f"        unit: {unit}")
            if kind == "sum":
                out.append("        sum: {value_type: int, aggregation: cumulative, monotonic: true}")
            else:
                out.append("        gauge: {value_type: int}")
            out.append("        column_oids:")
            out.append(f"          - oid: {oid}")
            out.append("            resource_attributes: [interface.name]")
    if with_markers:
        out.append(end)
    return "\n".join(out) + "\n"


def render_otel_processors(
    targets: list[dict],
    *,
    site: str = "home",
    job: str = "device_snmp",
    with_markers: bool = True,
) -> str:
    """Per-device resource processors.

    service.name → Prometheus `job`, service.instance.id → `instance`. Setting them
    is what lets the OTel path keep every selector that existed under
    snmp_exporter (FR-040).
    """
    begin, end = OTEL_MARKERS["processors"]
    out: list[str] = []
    if with_markers:
        out.append(begin)
        out.append("  # Generated — service.name becomes the Prometheus `job` label and")
        out.append("  # service.instance.id becomes `instance`, preserving existing selectors.")
    for tgt in targets:
        key = otel_receiver_key(tgt)
        out.append(f"  resource/{key}:")
        out.append("    attributes:")
        out.append(f"      - {{key: service.name,        value: {job}, action: upsert}}")
        out.append(f"      - {{key: service.instance.id, value: \"{tgt['ip']}\", action: upsert}}")
        out.append(f"      - {{key: device_name,         value: {tgt['name']}, action: upsert}}")
        out.append(f"      - {{key: role,                value: {tgt['role']}, action: upsert}}")
        out.append(f"      - {{key: vendor,              value: {tgt['vendor']}, action: upsert}}")
        out.append(f"      - {{key: site,                value: {site}, action: upsert}}")
    if with_markers:
        out.append(end)
    return "\n".join(out) + "\n"


def render_otel_pipelines(
    targets: list[dict],
    *,
    exporters: str = "prometheusremotewrite/prometheus, prometheusremotewrite/victoriametrics",
    with_markers: bool = True,
) -> str:
    begin, end = OTEL_MARKERS["pipelines"]
    out: list[str] = []
    if with_markers:
        out.append(begin)
    for tgt in targets:
        key = otel_receiver_key(tgt)
        out.append(f"    metrics/{key}:")
        out.append(f"      receivers: [snmp/{key}]")
        out.append(f"      processors: [memory_limiter, resource/{key}, batch]")
        out.append(f"      exporters: [{exporters}]")
    if with_markers:
        out.append(end)
    return "\n".join(out) + "\n"


def render_otel_device_map(
    targets: list[dict],
    *,
    syslog_devices: list[dict] | None = None,
    with_markers: bool = True,
) -> str:
    """OTTL statements mapping syslog sender IP → device_name.

    Sender IP beats the hostname inside the message: it is present on every
    datagram and cannot be shaped by message content.

    Covers the UNION of SNMP targets and syslog-only devices. Generating from SNMP
    targets alone silently dropped pfSense, a switch with no SNMP access, and the
    NetClaw host from this site's map — all of which send logs.
    """
    begin, end = OTEL_MARKERS["devicemap"]
    merged: dict[str, str] = {}
    for tgt in targets:
        merged[tgt["ip"]] = tgt["name"]
    for dev in syslog_devices or []:
        merged.setdefault(dev["ip"], dev["name"])
    out: list[str] = []
    if with_markers:
        out.append(begin)
        out.append("          # Generated — union of device_telemetry.snmp.targets and")
        out.append("          # device_telemetry.syslog.devices. Edit inventory, not this block.")
    width = max((len(n) for n in merged.values()), default=0)
    for ip, name in sorted(merged.items(), key=lambda kv: kv[1].lower()):
        pad = " " * (width - len(name))
        out.append(
            f'          - set(attributes["device_name"], "{name}"){pad}'
            f' where attributes["net.peer.ip"] == "{ip}"'
        )
    if with_markers:
        out.append(end)
    return "\n".join(out) + "\n"


def inject_marked_block(text: str, block: str, markers: tuple[str, str]) -> str:
    """Replace a BEGIN/END delimited region. Idempotent; raises if markers absent."""
    begin, end = markers
    if begin not in text or end not in text:
        raise KeyError(f"managed markers not found: {begin}")
    pre, rest = text.split(begin, 1)
    _, post = rest.split(end, 1)
    if post.startswith("\n"):
        post = post[1:]
    return pre + block.rstrip("\n") + "\n" + post


def load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def normalize_template(vendor: str | None, template: str | None) -> str:
    t = (template or vendor or "generic").strip().lower()
    if t in ("ios", "ios-xe", "catalyst", "nxos"):
        return "cisco"
    if t in ("pf", "pfsense-fw", "firewall-pfsense"):
        return "pfsense"
    if t not in VALID_TEMPLATES and t != "if_mib":
        return "generic"
    if t == "if_mib":
        return "generic"
    return t


def normalize_target(raw: dict) -> dict | None:
    ip = (raw.get("ip") or raw.get("address") or "").strip()
    if not ip:
        return None
    name = (raw.get("name") or ip).strip()
    role = (raw.get("role") or ROLE_DEFAULT).strip().lower()
    vendor = (raw.get("vendor") or "").strip().lower() or None
    template = normalize_template(vendor, raw.get("template"))
    if not vendor:
        vendor = template
    return {
        "name": name,
        "ip": ip,
        "role": role,
        "vendor": vendor,
        "template": template,
    }


def syslog_devices_from_convergence(cfg: dict) -> list[dict]:
    """Devices that send syslog but are not SNMP targets.

    The sender-IP → device_name map must cover every log source, not just the
    SNMP inventory. Missing entries are not fatal — device_name falls back to the
    message hostname and then the raw IP — but the label is then inconsistent with
    the SNMP inventory, which makes cross-signal correlation harder.
    """
    syslog = (cfg.get("device_telemetry") or {}).get("syslog") or {}
    out: list[dict] = []
    for d in syslog.get("devices") or []:
        ip = (d.get("ip") or d.get("address") or "").strip()
        name = (d.get("name") or "").strip()
        if ip and name:
            out.append({"name": name, "ip": ip})
    return out


def targets_from_convergence(cfg: dict) -> list[dict]:
    dt = (cfg.get("device_telemetry") or {}).get("snmp") or {}
    # Include targets even when enabled=false so dry-render still works;
    # apply decides whether to enable the profile.
    out: list[dict] = []
    for t in dt.get("targets") or []:
        n = normalize_target(t)
        if n:
            out.append(n)
    return out


def targets_from_file(doc: dict) -> list[dict]:
    out: list[dict] = []
    for t in doc.get("targets") or []:
        n = normalize_target(t)
        if n:
            out.append(n)
    return out


def sort_targets(targets: list[dict]) -> list[dict]:
    return sorted(targets, key=lambda t: (t["name"].lower(), t["ip"]))


def render_scrape(
    targets: list[dict],
    *,
    site: str = "home",
    exporter: str = "snmp-device-exporter:9116",
    poll_interval: str = "60s",
    with_markers: bool = True,
) -> str:
    """Render device_snmp job. Module per target via snmp_module label + relabel."""
    lines: list[str] = []
    if with_markers:
        lines.append(MARKER_BEGIN)
    lines.extend(
        [
            "  # Generated by scripts/render-convergence-telemetry.py — Phase 10",
            "  - job_name: device_snmp",
            f"    scrape_interval: {poll_interval}",
            "    metrics_path: /snmp",
            "    params:",
            "      module: [generic]",
            "      auth: [public_v2]",
            "    static_configs:",
        ]
    )
    if not targets:
        lines.append(
            "      []  # no targets — set device_telemetry.snmp.targets in convergence.yaml"
        )
    for t in targets:
        lines.append(f'      - targets: ["{t["ip"]}"]')
        lines.append("        labels:")
        lines.append(f"          site: {site}")
        lines.append(f"          device_name: {t['name']}")
        lines.append(f"          role: {t['role']}")
        lines.append(f"          vendor: {t['vendor']}")
        lines.append(f"          snmp_module: {t['template']}")
    lines.extend(
        [
            "    relabel_configs:",
            "      - source_labels: [__address__]",
            "        target_label: __param_target",
            "      - source_labels: [__param_target]",
            "        target_label: instance",
            "      - source_labels: [snmp_module]",
            "        target_label: __param_module",
            "      - target_label: __address__",
            f"        replacement: {exporter}",
        ]
    )
    if with_markers:
        lines.append(MARKER_END)
    lines.append("")
    return "\n".join(lines)


def load_module_body(modules_dir: Path, template_id: str) -> dict:
    path = modules_dir / f"{template_id}.yml"
    if not path.is_file():
        # Fall back to generic
        path = modules_dir / "generic.yml"
    if not path.is_file():
        raise FileNotFoundError(f"Missing SNMP module template: {path}")
    body = load_yaml(path)
    if not isinstance(body, dict):
        raise ValueError(f"Module {path} must be a mapping (walk/metrics)")
    return body


def render_snmp_yml(
    targets: list[dict],
    *,
    modules_dir: Path,
    community: str = "public",
    include_if_mib_alias: bool = True,
) -> str:
    needed = sorted({t["template"] for t in targets} | set(VALID_TEMPLATES))
    # Always ship all three vendor modules so apply is stable; if_mib alias optional.
    modules: dict[str, dict] = {}
    for tid in VALID_TEMPLATES:
        modules[tid] = load_module_body(modules_dir, tid)
    if include_if_mib_alias:
        modules["if_mib"] = load_module_body(modules_dir, "if_mib")

    doc = {
        "auths": {
            "public_v2": {
                "community": community,
                "version": 2,
            }
        },
        "modules": modules,
    }
    header = (
        "# Generated by scripts/render-convergence-telemetry.py — Phase 10\n"
        f"# templates_in_use: {', '.join(needed) if targets else '(none)'}\n"
        "# Community from SNMP_COMMUNITY env at apply time — do not commit real secrets.\n"
        "# snmp_exporter v0.26+ auth-split; per-metric ifDescr/ifName lookups.\n\n"
    )
    body = yaml.dump(
        doc,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )
    return header + body


def detect_syslog_host() -> str:
    # Prefer primary outbound interface IP; fall back to hostname.
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except OSError:
        try:
            return socket.gethostbyname(socket.gethostname())
        except OSError:
            return "<convergence-host-ip>"


def render_checklist(
    targets: list[dict],
    *,
    site: str,
    syslog_host: str | None = None,
    syslog_port: int = 1514,
    community_env: str = "SNMP_COMMUNITY",
) -> str:
    host = syslog_host or detect_syslog_host()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Device telemetry config checklist — site `{site}`",
        "",
        f"Generated: {now}  ",
        "By: `scripts/render-convergence-telemetry.py` (Phase 10)  ",
        "",
        "Secrets stay in env — **never** commit community strings.",
        "",
        "## Convergence collector endpoints",
        "",
        f"| Item | Value |",
        f"|------|-------|",
        f"| SNMP community env | `{community_env}` (set in `deploy/convergence/.env`) |",
        f"| Syslog destination | `{host}` UDP port **{syslog_port}** |",
        f"| SNMP poller | Convergence snmp_exporter (compose profile `device-snmp`) |",
        "",
        "## Inventory targets",
        "",
        "| Name | IP | Role | Vendor | Template |",
        "|------|-----|------|--------|----------|",
    ]
    if not targets:
        lines.append("| _(none)_ | | | | |")
    for t in targets:
        lines.append(
            f"| {t['name']} | {t['ip']} | {t['role']} | {t['vendor']} | {t['template']} |"
        )
    lines.extend(
        [
            "",
            "## SNMP (read-only) — device side",
            "",
            f"Set a read-only community and put the same value in `{community_env}` on the NetClaw host.",
            "",
            "### Cisco IOS / IOS-XE",
            "",
            "```text",
            f"snmp-server community <value-from-{community_env}> RO",
            "! optional: snmp-server location ...",
            "```",
            "",
            "### pfSense",
            "",
            "1. **Services → SNMP** — enable SNMP, set read community to match "
            f"`{community_env}`.",
            "2. Ensure LAN/mgmt ACL allows the Convergence host to poll UDP/161.",
            "",
            "## Syslog — device side",
            "",
            f"Send device syslog to **{host}:{syslog_port}** (UDP or TCP) when "
            "`device_telemetry.syslog.enabled` / profile `device-syslog` is on.",
            "",
            "Vendor-default **RFC3164/BSD** is accepted — the Convergence syslog "
            "gateway converts it to RFC5424 for Loki, so no special log format is "
            "required on the device.",
            "",
            "### Cisco",
            "",
            "```text",
            f"logging host {host} transport udp port {syslog_port}",
            "logging trap informational",
            "! send the hostname so Loki device_name matches this inventory",
            "! (otherwise device_name falls back to the sending IP)",
            "logging origin-id hostname",
            "service timestamps log datetime msec localtime show-timezone",
            "```",
            "",
            "### pfSense",
            "",
            f"**Status → System Logs → Settings** (or **Services → Syslog**): remote "
            f"server `{host}`, port `{syslog_port}`.",
            "",
            "## Verify (after apply)",
            "",
            "```bash",
            "./scripts/convergence-telemetry-apply.sh   # if not already applied",
            "./deploy/convergence/smoke-device-snmp.sh",
            "# Named interfaces:",
            "curl -sG 'http://127.0.0.1:9090/api/v1/query' \\",
            "  --data-urlencode 'query=count by (device_name,interface_name) (interface_status)'",
            "# Grafana: http://127.0.0.1:3300 → folder Convergence",
            "```",
            "",
            "## Full vendor MoP",
            "",
            "See `deploy/convergence/adapters/device-snmp/device-config-snippets.md` "
            "for complete Cisco / pfSense / generic steps (T131).",
            "",
            "## Non-goals (v1)",
            "",
            "- Auto-push of this config onto devices (checklist only).",
            "- Committing real community strings.",
            "",
        ]
    )
    return "\n".join(lines)


def inject_managed_section(prometheus_yml: str, scrape_block: str) -> str:
    """Replace or append managed device_snmp section in prometheus.yml text."""
    begin = MARKER_BEGIN
    end = MARKER_END
    # scrape_block already includes markers when with_markers=True
    if begin in prometheus_yml and end in prometheus_yml:
        pre, rest = prometheus_yml.split(begin, 1)
        _, post = rest.split(end, 1)
        # drop leading newline duplication
        if post.startswith("\n"):
            post = post[1:]
        return pre + scrape_block.rstrip("\n") + "\n" + post

    # No markers: try replace existing un-marked device_snmp job, else append.
    lines = prometheus_yml.splitlines(keepends=True)
    out: list[str] = []
    i = 0
    replaced = False
    while i < len(lines):
        line = lines[i]
        # Detect start of device_snmp job (possibly with preceding comments)
        if (
            not replaced
            and line.lstrip().startswith("- job_name: device_snmp")
        ):
            # Walk back comment lines that are part of the job header
            # (already emitted? keep simple: drop from this line until next job or EOF)
            # Remove trailing comments immediately above that we already wrote?
            # Pop prior comment block about device_snmp if present
            while out and (
                out[-1].lstrip().startswith("#")
                or out[-1].strip() == ""
            ):
                # only strip comments that mention device_snmp / Campus
                prev = out[-1]
                if prev.strip() == "":
                    break
                if "device_snmp" in prev or "Campus/wired" in prev or "Phase 8" in prev:
                    out.pop()
                    continue
                break
            # skip until next top-level job or end of scrape_configs-ish
            i += 1
            while i < len(lines):
                nxt = lines[i]
                if nxt.startswith("  - job_name:"):
                    break
                if nxt.startswith("scrape_configs:") or (
                    nxt and not nxt[0].isspace() and not nxt.lstrip().startswith("#")
                ):
                    break
                i += 1
            # insert managed block (ensure indentation at job level)
            block = scrape_block
            if not block.endswith("\n"):
                block += "\n"
            out.append("\n" if out and not out[-1].endswith("\n") else "")
            # strip accidental double blank
            out.append(block if block.startswith("  ") or block.startswith("#") else block)
            replaced = True
            continue
        out.append(line)
        i += 1

    if not replaced:
        # Append before end of file
        text = "".join(out).rstrip() + "\n\n" + scrape_block.rstrip() + "\n"
        return text
    return "".join(out)


def render_suzieq_inventory(
    targets: list[dict],
    site: str = "home",
    namespace: str | None = None,
    ignore_known_hosts: bool = True,
    exclude_roles: list[str] | None = None,
) -> str:
    """Render a SuzieQ native inventory YAML from the convergence target list.

    Produces the same inventory that would otherwise be hand-authored for the
    SuzieQ poller. Credentials come from env vars at runtime — the rendered
    file contains ${SUZIEQ_DEVICE_USER} / ${SUZIEQ_DEVICE_PASSWORD} references
    that the deploy adapter resolves (just like SNMP_COMMUNITY for OTel).

    Args:
        targets: Normalized target dicts (name, ip, role, vendor, template).
        site: Site label — used as the SuzieQ namespace unless overridden.
        namespace: Override the namespace name (default: site).
        ignore_known_hosts: Set ignore-known-hosts on the default device entry.
        exclude_roles: Roles to skip (e.g. ["firewall"] for unsupported vendors).
    """
    ns = namespace or site
    exclude = set(r.lower() for r in (exclude_roles or []))

    filtered = [t for t in targets if t["role"] not in exclude]
    if not filtered:
        return f"# No targets after excluding roles: {sorted(exclude)}\n"

    # Map vendor to SuzieQ devtype
    vendor_to_devtype = {
        "cisco": "iosxe",
        "pfsense": None,  # unsupported
        "generic": None,
    }

    hosts = []
    for t in filtered:
        devtype = vendor_to_devtype.get(t["vendor"], None)
        if devtype is None:
            # Skip unsupported vendors rather than producing a bad inventory
            continue
        host_line = (
            f"ssh://${{SUZIEQ_DEVICE_USER}}:${{SUZIEQ_DEVICE_PASSWORD}}"
            f"@{t['ip']} devtype={devtype}"
        )
        hosts.append(f"      - url: {host_line}")

    if not hosts:
        return "# No SuzieQ-compatible targets found (unsupported vendors only)\n"

    lines = [
        "# Auto-generated by render-convergence-telemetry.py (Phase 12, T161)",
        f"# {len(hosts)} device(s), namespace={ns}",
        f"# Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "#",
        "# Credentials: set SUZIEQ_DEVICE_USER and SUZIEQ_DEVICE_PASSWORD in",
        "# deploy/convergence/.env — NEVER commit secrets to this file.",
        "",
        "sources:",
        f"  - name: {ns}",
        "    hosts:",
        *hosts,
        "",
        "devices:",
        "  - name: default",
    ]
    if ignore_known_hosts:
        lines.append("    ignore-known-hosts: true")
    lines += [
        "",
        "namespaces:",
        f"  - name: {ns}",
        f"    source: {ns}",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Render Convergence device telemetry (Phase 10)"
    )
    ap.add_argument("--config", type=Path, help="convergence.yaml")
    ap.add_argument("--targets", type=Path, help="targets YAML (targets: [...])")
    ap.add_argument("--site", default=None, help="override site label")
    ap.add_argument(
        "--modules-dir",
        type=Path,
        default=DEFAULT_MODULES_DIR,
        help="vendor module templates directory",
    )
    ap.add_argument(
        "--exporter",
        default="snmp-device-exporter:9116",
        help="Prometheus scrape replacement for snmp_exporter",
    )
    ap.add_argument(
        "--community",
        default=os.environ.get("SNMP_COMMUNITY", "public"),
        help="SNMPv2c community for snmp.yml (default SNMP_COMMUNITY or public)",
    )
    ap.add_argument("--poll-interval", default="60s")
    ap.add_argument(
        "--out-scrape",
        type=Path,
        help="write scrape fragment (use - for stdout via --print-scrape)",
    )
    ap.add_argument(
        "--out-snmp",
        type=Path,
        help="write full snmp_exporter snmp.yml",
    )
    ap.add_argument(
        "--out-checklist",
        type=Path,
        help="write device config checklist markdown",
    )
    ap.add_argument(
        "--out-suzieq",
        type=Path,
        help="write SuzieQ native inventory YAML (Phase 12, T161)",
    )
    ap.add_argument(
        "--suzieq-namespace",
        default=None,
        help="SuzieQ namespace name (default: site name)",
    )
    ap.add_argument(
        "--suzieq-exclude-roles",
        default="firewall",
        help="comma-separated roles to exclude from SuzieQ inventory (default: firewall)",
    )
    ap.add_argument(
        "--inject-prometheus",
        type=Path,
        help="read/write this prometheus.yml with managed section",
    )
    ap.add_argument(
        "--syslog-host",
        default=None,
        help="override syslog destination IP in checklist",
    )
    ap.add_argument(
        "--syslog-port",
        type=int,
        default=1514,
    )
    ap.add_argument(
        "--inject-otel",
        type=Path,
        help="read/write the OTel Collector config, replacing its managed sections "
             "(snmp receivers, per-device resource processors, metrics pipelines, "
             "and the syslog sender-IP → device_name map)",
    )
    ap.add_argument(
        "--otel-job",
        default="device_snmp",
        help="Prometheus job label the collector should claim (service.name). "
             "Use a distinct value (e.g. device_snmp_otel) to stage alongside an "
             "existing writer before cutting over.",
    )
    ap.add_argument(
        "--print-otel",
        action="store_true",
        help="print the OTel managed blocks to stdout",
    )
    ap.add_argument(
        "--print-scrape",
        action="store_true",
        help="print scrape fragment to stdout",
    )
    ap.add_argument(
        "--no-markers",
        action="store_true",
        help="omit BEGIN/END markers in scrape fragment",
    )
    args = ap.parse_args()

    if not args.config and not args.targets:
        ap.error("need --config or --targets")

    site = args.site or "home"
    poll = args.poll_interval
    targets: list[dict] = []

    if args.targets:
        doc = load_yaml(args.targets)
        targets = targets_from_file(doc)
        if doc.get("site"):
            site = str(doc["site"])
    if args.config:
        cfg = load_yaml(args.config)
        if not args.targets:
            targets = targets_from_convergence(cfg)
        if cfg.get("site") and not args.site:
            site = str(cfg["site"])
        snmp = (cfg.get("device_telemetry") or {}).get("snmp") or {}
        if snmp.get("poll_interval") and args.poll_interval == "60s":
            poll = str(snmp["poll_interval"])
        syslog = (cfg.get("device_telemetry") or {}).get("syslog") or {}
        listen = str(syslog.get("listen") or "")
        if listen and ":" in listen and args.syslog_port == 1514:
            try:
                args.syslog_port = int(listen.rsplit(":", 1)[-1])
            except ValueError:
                pass

    targets = sort_targets(targets)
    syslog_devices = syslog_devices_from_convergence(cfg) if args.config else []
    scrape = render_scrape(
        targets,
        site=site,
        exporter=args.exporter,
        poll_interval=poll,
        with_markers=not args.no_markers,
    )

    if args.print_scrape or (args.out_scrape and str(args.out_scrape) == "-"):
        sys.stdout.write(scrape if scrape.endswith("\n") else scrape + "\n")
    elif args.out_scrape:
        args.out_scrape.parent.mkdir(parents=True, exist_ok=True)
        args.out_scrape.write_text(
            scrape if scrape.endswith("\n") else scrape + "\n", encoding="utf-8"
        )
        print(f"Wrote scrape → {args.out_scrape} ({len(targets)} targets)", file=sys.stderr)

    if args.out_snmp:
        snmp_text = render_snmp_yml(
            targets,
            modules_dir=args.modules_dir,
            community=args.community,
        )
        args.out_snmp.parent.mkdir(parents=True, exist_ok=True)
        args.out_snmp.write_text(snmp_text, encoding="utf-8")
        print(f"Wrote snmp.yml → {args.out_snmp}", file=sys.stderr)

    if args.out_checklist:
        md = render_checklist(
            targets,
            site=site,
            syslog_host=args.syslog_host,
            syslog_port=args.syslog_port,
        )
        args.out_checklist.parent.mkdir(parents=True, exist_ok=True)
        args.out_checklist.write_text(md, encoding="utf-8")
        print(f"Wrote checklist → {args.out_checklist}", file=sys.stderr)

    if args.out_suzieq:
        exclude_roles = [
            r.strip() for r in (args.suzieq_exclude_roles or "").split(",") if r.strip()
        ]
        suzieq_inv = render_suzieq_inventory(
            targets,
            site=site,
            namespace=args.suzieq_namespace,
            ignore_known_hosts=True,
            exclude_roles=exclude_roles,
        )
        args.out_suzieq.parent.mkdir(parents=True, exist_ok=True)
        args.out_suzieq.write_text(suzieq_inv, encoding="utf-8")
        print(f"Wrote SuzieQ inventory → {args.out_suzieq}", file=sys.stderr)

    otel_blocks = {
        "receivers": render_otel_receivers(targets, poll_interval=poll),
        "processors": render_otel_processors(targets, site=site, job=args.otel_job),
        "pipelines": render_otel_pipelines(targets),
        "devicemap": render_otel_device_map(targets, syslog_devices=syslog_devices),
    }

    if args.print_otel:
        for key in ("receivers", "processors", "pipelines", "devicemap"):
            sys.stdout.write(otel_blocks[key])
            sys.stdout.write("\n")

    if args.inject_otel:
        src = args.inject_otel
        if not src.is_file():
            print(f"otel config not found: {src}", file=sys.stderr)
            return 1
        text = src.read_text(encoding="utf-8")
        try:
            for key in ("receivers", "processors", "pipelines", "devicemap"):
                text = inject_marked_block(text, otel_blocks[key], OTEL_MARKERS[key])
        except KeyError as exc:
            print(
                f"{exc}\nThe collector config must contain the managed markers. "
                "See deploy/convergence/otel/snmp-receivers.md.",
                file=sys.stderr,
            )
            return 1
        src.write_text(text, encoding="utf-8")
        print(
            f"Injected OTel managed sections → {src} "
            f"({len(targets)} device(s), job={args.otel_job})",
            file=sys.stderr,
        )

    if args.inject_prometheus:
        src = args.inject_prometheus
        if not src.is_file():
            print(f"prometheus.yml not found: {src}", file=sys.stderr)
            return 1
        original = src.read_text(encoding="utf-8")
        updated = inject_managed_section(original, scrape)
        src.write_text(updated, encoding="utf-8")
        print(f"Injected managed device_snmp section → {src}", file=sys.stderr)

    if not any(
        [
            args.out_scrape,
            args.out_snmp,
            args.out_checklist,
            args.out_suzieq,
            args.inject_prometheus,
            args.print_scrape,
            args.inject_otel,
            args.print_otel,
        ]
    ):
        # Default: print scrape
        sys.stdout.write(scrape if scrape.endswith("\n") else scrape + "\n")

    print(
        f"Rendered {len(targets)} target(s) site={site} "
        f"templates={sorted({t['template'] for t in targets}) or ['(none)']}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
