FROM python:3.12-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends libsnappy1v5 libsnappy-dev gcc \
    && pip install --no-cache-dir prometheus_client kafka-python python-snappy \
    && apt-get purge -y gcc \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY bgp-normalizer.py .

ENV BMP_EXPORTER_PORT=9100
EXPOSE 9100

CMD ["python3", "-u", "bgp-normalizer.py"]