import { runtimeInfo } from '../shared/runtime-client.js';
import React, { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { VIEWS, GUIDES, age, bgpEntities, clawInventory, entities, list, money, observation, selectedContext, text } from './model.js';
import { previewSources, previewAssessment } from './fixtures.js';
import { ClawInventory, TokenomicsView, DocumentationView, LogsView, SecurityView, SecurityOverview } from './ReferenceViews.jsx';
import { RagView, ConfigurationView } from './WorkspaceTools.jsx';
import StandardChat from './StandardChat.jsx';
import Pal from './Pal.jsx';
import { controlUiHref } from '../hud-server/control-ui.js';
import AssessmentView from './Assessment.jsx';
const Scene = lazy(() => import('./Scene.jsx'));
const ENDPOINTS = { graph: '/api/graph', n2n: '/api/n2n', gateway: '/api/gateway/status', budget: '/api/budget/status', bgp: '/api/bgp', runtime: '/api/hud/runtime', security: '/api/hud/security' };
const isPreview = () => globalThis.NETCLAW_PREVIEW === true;
function Badge({ children }) { const label = text(children); return <span className={`badge ${/unreachable|stale|failed|degraded|unavailable/i.test(label) ? 'warning' : /ready|live|connected|configured|available/i.test(label) ? 'good' : ''}`}>{label}</span>; }
function Source({ source, name }) { return <p className="source"><span>{name}</span><span>{source?.lastSuccess ? `Read ${age(source.lastSuccess)}` : 'No successful read'}{source?.state !== 'available' ? ` · ${text(source?.state, 'Loading')}` : ''}</span></p>; }
function Panel({ title, eyebrow, children, action, className = '' }) { return <section className={`panel ${className}`}><div className="section-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action}</div>{children}</section>; }
function useSources(preview) {
  const [sources, setSources] = useState(() => preview ? (globalThis.NETCLAW_PREVIEW_SOURCES || previewSources()) : {}), [refresh, setRefresh] = useState(0);
  useEffect(() => {
    if (preview) return;
    let disposed = false, timer; const controllers = new Set();
    const poll = async () => {
      if (document.hidden) { timer = setTimeout(poll, 15000); return; }
      await Promise.allSettled(Object.entries(ENDPOINTS).map(async ([key, endpoint]) => {
        const controller = new AbortController(); controllers.add(controller); const timeout = setTimeout(() => controller.abort(), 20000);
        try { const response = await fetch(endpoint, { signal: controller.signal, cache: 'no-store' }); if (!response.ok) throw Error(); const payload = await response.json(); if (!disposed) setSources(s => ({ ...s, [key]: observation(s[key], payload) })); }
        catch { if (!disposed) setSources(s => ({ ...s, [key]: observation(s[key], null, true) })); }
        finally { clearTimeout(timeout); controllers.delete(controller); }
      }));
      if (!disposed) timer = setTimeout(poll, 30000);
    }; poll();
    return () => { disposed = true; clearTimeout(timer); controllers.forEach(c => c.abort()); };
  }, [preview, refresh]);
  return [sources, () => setRefresh(x => x + 1)];
}
export default function Dashboard() {
  const [cloudPalOpen, setCloudPalOpen] = useState(false);
  const preview = isPreview();
  const selectedRuntime = runtimeInfo();
  const isHermes = selectedRuntime?.kind === 'hermes';
  const [sources, refresh] = useSources(preview);
  const [view, setView] = useState('chat'), [mode, setMode] = useState(() => { try { return localStorage.getItem('nc-hud-mode') === 'advanced' ? 'advanced' : 'basic'; } catch { return 'basic'; } });
  const [search, setSearch] = useState(''), [selected, setSelected] = useState(null), [three, setThree] = useState(false), [canvasLoaded, setCanvasLoaded] = useState(false), [canvasReady, setCanvasReady] = useState(false), [pending, setPending] = useState(null), [notice, setNotice] = useState('');
  const [assessment, setAssessment] = useState({ records: [] }), [more, setMore] = useState(false);
  const [logSource,setLogSource] = useState('mesh');
  const frame = useRef(null), heading = useRef(null), detailSeq = useRef(0);
  const graph = sources.graph?.payload || {}, feed = sources.n2n?.payload || {}, gateway = sources.gateway?.payload || {};
  const rows = useMemo(() => entities(feed), [feed]);
  const query = search.trim().toLowerCase();
  const shown = rows.filter(r => (view === 'risk' ? r.kind === 'member' : view === 'neighbours' ? r.kind === 'peer' : view === 'mobile' ? r.kind === 'edge' : true) && `${r.name} ${r.identity} ${r.status}`.toLowerCase().includes(query));
  const picked = rows.find(r => r.key === selected);
  const bgpRows = useMemo(() => bgpEntities(sources.bgp?.payload), [sources.bgp?.payload]);
  const pickedBgp = bgpRows.find(row => row.key === selected);
  const counts = Object.fromEntries(['member', 'peer', 'edge', 'advisor'].map(kind => [kind, rows.filter(r => r.kind === kind).length]));
  const nav = id => { detailSeq.current++; setAssessment({ records: [] }); setView(id); setSelected(null); setNotice(''); if (id === 'canvas') setCanvasLoaded(true); setMore(false); requestAnimationFrame(() => heading.current?.focus()); };
  const investigate = (title, data, source = 'Operator-selected context', retrievedAt) => { setPending(selectedContext(title, data, source, retrievedAt)); setCanvasLoaded(true); setView('canvas'); };
  useEffect(() => { try { localStorage.setItem('nc-hud-mode', mode); } catch {} }, [mode]);
  useEffect(() => {
    const message = async event => {
      if (event.origin !== location.origin || event.source !== frame.current?.contentWindow) return;
      if (event.data?.type === 'netclaw:session-changed') { detailSeq.current++; setAssessment({ records: [] }); }
      if (event.data?.type === 'netclaw:canvas-ready') setCanvasReady(true);
      if (event.data?.type === 'netclaw:context-accepted') { setPending(null); setNotice('Context added to the active draft. Review it before sending.'); }
      if (event.data?.type === 'netclaw:context-rejected') setNotice('Canvas is busy. Wait for the current reply or save, then try again.');
      if (event.data?.type === 'netclaw:assessment') {
        const ref = event.data.reference; if (!ref?.taskRef || !ref?.assessmentId) return;
        const seq = ++detailSeq.current; setView('science'); setAssessment({ loading: true, records: [] });
        try { const result = await fetch(`/api/hud/tasks/${encodeURIComponent(ref.taskRef)}/assessments/${encodeURIComponent(ref.assessmentId)}`, { cache: 'no-store' }); if (!result.ok) throw Error(); const data = await result.json(); if (seq === detailSeq.current) setAssessment({ records: data.records || [], audit: data.audit }); }
        catch { if (seq === detailSeq.current) setAssessment({ records: [], error: 'Assessment unavailable. Its task ownership could not be verified, or the source could not be read.' }); }
      }
    }; window.addEventListener('message', message); return () => window.removeEventListener('message', message);
  }, []);
  const sendContext = () => { frame.current?.contentWindow.postMessage({ type: 'netclaw:context', content: pending }, location.origin); };
  const openClawHref = !preview && sources.runtime?.state === 'available' ? controlUiHref(sources.runtime.payload?.controlUi) : null;
  const openClawReason = preview ? 'Native OpenClaw is disabled in synthetic preview.' : sources.runtime?.payload?.controlUi?.reason || 'OpenClaw UI configuration unavailable. Check the gateway configuration and refresh.';
  const title = VIEWS.find(v => v[0] === view)?.[1] || 'Overview';
  const common = <div className="quick-actions"><button onClick={() => investigate('Network health', 'Review the current network health in my authorized scope. Capture observations and source times before drawing conclusions.')}>Review network health <span>↗</span></button><button onClick={() => investigate('Current work', 'Summarize current work, required approvals and verification gaps from available task evidence.')}>Review current work <span>↗</span></button><button onClick={() => nav('canvas')}>Open context canvas <span>↗</span></button></div>;
  const entityTable = <><Source source={sources.n2n} name="Federation snapshot"/><div className="table-scroll"><table><thead><tr><th>Claw / device</th><th>State</th><th>Last seen</th>{mode === 'advanced' && <th>Authority</th>}<th><span className="sr-only">Inspect</span></th></tr></thead><tbody>{shown.map(row => <tr key={row.key} className={selected === row.key ? 'selected' : ''}><td><strong>{row.name}</strong><small>{row.identity}</small><small>LLM: {clawInventory(row).model}</small></td><td><Badge>{row.status}</Badge></td><td>{age(row.seen)}{row.freshness === "stale" && <small>Stale observation</small>}</td>{mode === 'advanced' && <td>{row.authority}</td>}<td><button aria-label={`Inspect ${row.name}`} onClick={() => setSelected(row.key)}>Inspect ↗</button></td></tr>)}</tbody></table>{!shown.length && <div className="empty"><h3>{query ? 'No matching entities' : sources.n2n?.state === 'available' ? 'No entities reported in this scope' : 'Federation data unavailable'}</h3><p>{query ? 'Try another name or identity.' : 'No device-health conclusion follows from an empty or unavailable feed.'}</p></div>}</div></>;
  return <div className="hud-shell">
    <aside className="nav-rail"><a className="brand" href="#overview" onClick={e => { e.preventDefault(); nav('overview'); }}><span className="brand-mark">N<span>›</span></span><div>NETCLAW<small>OPERATIONS WORKSPACE</small></div></a><div className="installation"><span className="status-dot"/><div><strong>{text(feed.risk?.risk_name || feed.risk?.name || graph.identity?.name, 'Local NetClaw')}</strong><small>{text(feed.risk?.role, 'Role not reported')} · {preview ? 'PREVIEW' : 'LOCAL'}</small></div></div>
      <nav aria-label="Main navigation">{VIEWS.filter((v,i) => v[0] !== 'pal' && (mode === 'advanced' || more || i < 7 || ['rag','configuration','tokenomics','documentation','logs','security'].includes(v[0]) || v[0] === view)).map(([id,label,num]) => <button key={id} className={view === id || (id === 'chat' && view === 'pal') ? 'active' : ''} aria-current={view === id || (id === 'chat' && view === 'pal') ? 'page' : undefined} onClick={() => nav(id)}><span className="nav-num">{num}</span>{label}{id === 'science' && <span className="nav-tag">JEV</span>}</button>)}{mode === 'basic' && <button className="more-nav" onClick={() => setMore(!more)}>{more ? '− Fewer destinations' : '+ More destinations'}</button>}</nav>
      <div className="nav-bottom"><span className="eyebrow">Investigation workspace</span><p>Context stays with the conversation.</p><button onClick={() => nav('canvas')}>Canvas <span>↗</span></button><a href="/classic.html" target="_blank" rel="noreferrer">Classic HUD & utilities ↗</a></div>
    </aside>
    <div className="main-column"><header className="command-bar"><div className="breadcrumb">NETCLAW <span>/</span> {title} {selectedRuntime && <span>· {selectedRuntime.label}</span>}</div><div className="mode-toggle" role="group" aria-label="Experience level"><button aria-pressed={mode === 'basic'} onClick={() => setMode('basic')}>Basic</button><button aria-pressed={mode === 'advanced'} onClick={() => setMode('advanced')}>Advanced</button></div><div className="chat-switch" role="group" aria-label="Chat interface"><button aria-pressed={view === 'chat'} onClick={() => nav('chat')}>Chat</button><button aria-pressed={view === 'canvas'} onClick={() => nav('canvas')}>Canvas</button>{openClawHref ? <a href={openClawHref} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer" title="Open native OpenClaw in a separate tab. Its own authentication and conversation history apply. Forward the gateway port as well when using SSH.">OpenClaw ↗</a> : <span className="chat-unavailable"><button disabled title={openClawReason}>{isHermes ? 'Hermes · HUD' : 'OpenClaw ↗'}</button><span className="sr-only">{openClawReason}</span></span>}<button aria-pressed={view === 'pal'} onClick={() => nav('pal')}>Avatar</button></div></header>
      {preview && <div className="preview-banner">SYNTHETIC PREVIEW · Illustrative records only. No live network operations or paid inference.</div>}
      <main><div className="page-heading"><div><span className="eyebrow">{view === 'overview' ? 'Your network, in context' : 'NetClaw workspace'}</span><h1 tabIndex={-1} ref={heading}>{title}<span className="title-dot">.</span></h1><p>{view === 'overview' ? 'What is available. What needs attention. Where to investigate next.' : view === 'chat' ? 'A straightforward conversation. Keep the context, ask the next question.' : view === 'pal' ? 'A voice companion, connected to your local NetClaw.' : view === 'canvas' ? 'Your branches, sources and conversations stay together.' : 'Inspect the source, then continue the investigation.'}</p></div><div className="heading-actions"><Badge>{isHermes ? sources.runtime ? sources.runtime.state === 'available' && sources.runtime.payload?.ready ? 'Hermes ready' : 'Hermes unavailable' : 'Connecting to Hermes' : sources.gateway ? gateway.online ? 'Gateway available' : 'Gateway unavailable' : 'Connecting'}</Badge><button onClick={refresh} disabled={preview} aria-label="Refresh dashboard sources">↻ Refresh</button></div></div>
      {notice && <p className="notice" role="status">{notice}</p>}
      {!['canvas', 'chat', 'pal'].includes(view) && <div className="search-row"><label className="search-box"><span>⌕</span><input aria-label="Search entities and capabilities" placeholder="Search entities, skills or capabilities…" value={search} onChange={e => setSearch(e.target.value)}/></label>{query && <button onClick={() => nav('integrations')}>Search capabilities ↗</button>}<span className="read-label">● SOURCE-ATTRIBUTED VIEWS</span></div>}
      {view === 'overview' && <><SecurityOverview settings={sources.security?.payload} posture={feed.posture} sourceAvailable={sources.n2n?.state==='available'} onOpen={() => nav('security')}/><div className="metric-grid">{[['Execution members', counts.member, 'risk'], ['External neighbours', counts.peer, 'neighbours'], ['Mobile edges', counts.edge, 'mobile'], ['Science Officers', counts.advisor, 'science']].map(([label,count,destination]) => <button className="metric-card" key={label} onClick={() => nav(destination)}><span>{label}<i>↗</i></span><strong>{sources.n2n?.state === 'available' || destination === 'science' && count ? String(count).padStart(2, '0') : '—'}</strong><small>{sources.n2n?.state === 'available' ? 'Reported in this scope' : 'Source unavailable'}</small></button>)}</div>
        <div className="overview-grid"><Panel title="Attention & availability" eyebrow="Start here" action={<span className="panel-index">01 /</span>}>
          {rows.filter(r => r.freshness === "stale" || /unreachable|stale|degraded|offline/i.test(r.status)).map(r => <button className="attention-row" key={r.key} onClick={() => { setSelected(r.key); setView(r.kind === 'peer' ? 'neighbours' : r.kind === 'edge' ? 'mobile' : 'risk'); }}><span className="attention-icon">!</span><div><strong>{r.name}</strong><p>{r.status} · last seen {age(r.seen)}</p></div><span>↗</span></button>)}
          {Object.entries(sources).filter(([,s]) => s.state !== 'available').map(([name,s]) => <div className="attention-row" key={name}><span className="attention-icon neutral">?</span><div><strong>{name === 'bgp' ? 'Routing source' : name} unavailable</strong><p>{text(s.error, 'No successful live read')} · {s.lastSuccess ? `last success ${age(s.lastSuccess)}` : 'No health conclusion'}</p></div></div>)}
          {!Object.keys(sources).length && <p className="empty">Reading local sources…</p>}
          <Source source={sources.n2n} name="Federation & gateway"/>
        </Panel><Panel title="Start an investigation" eyebrow="Ask Border" className="investigate-panel">{common}<div className="canvas-note"><span className="node-sketch">□ ── □<br/>　└── □</span><p>Branch a question.<br/>Compare the evidence.<br/>Keep the context.</p></div></Panel></div>
        <div className="overview-grid"><Panel title="Capability library" eyebrow="Available knowledge"><div className="library-count"><strong>{list(graph.integrations).length || '—'}</strong><p>catalogued integrations<br/><span>{list(graph.skills).length} skills · not a reachability count</span></p></div><div className="tag-list">{list(graph.integrations).slice(0,8).map(i => <button key={i.id} onClick={() => { setSearch(i.name); nav('integrations'); }}>{i.name}</button>)}</div><button className="text-button" onClick={() => nav('integrations')}>Explore all capabilities →</button><Source source={sources.graph} name="Installed skill catalogue"/></Panel><Panel title="Jev · Science Officer" eyebrow="Advice with provenance" className="science-card"><div className="science-emblem">✧</div><h3>{text(list(feed.advisors)[0]?.status, 'Not configured or unavailable')}</h3><p>Questions, typed judgments and Border's interpretation, tied to the originating task.</p><button className="text-button" onClick={() => nav('science')}>Inspect Science Officer →</button><p className="muted">Advisory only. Model agreement is not proof.</p></Panel></div>
      </>}
      {['risk','neighbours','mobile'].includes(view) && <div className={picked ? 'with-inspector' : ''}><Panel title={view === 'risk' ? 'Internal execution members' : view === 'mobile' ? 'Enrolled mobile & edge devices' : 'External federation'} eyebrow={view === 'risk' ? 'iN2N / Risk of Claws' : view === 'mobile' ? 'Edge capabilities' : 'eN2N / trust boundary'} action={<button onClick={() => setThree(!three)} aria-pressed={three}>{three ? 'Hide 3D' : 'Explore in 3D'}</button>}>
        {three && <Suspense fallback={<p>Loading relationship view…</p>}><Scene rows={shown} onSelect={setSelected}/></Suspense>}{entityTable}
        {view === 'risk' && <details><summary>Reported enforcement posture</summary><pre>{JSON.stringify(feed.posture || { status: 'Not recorded' }, null, 2)}</pre></details>}
        {view === 'mobile' && <p className="muted">A disconnected device is not unenrolled. Capture and notifications use the existing operator consent workflow.</p>}
      </Panel>{picked && <Panel title={picked.name} eyebrow={picked.kind} className="inspector" action={<button onClick={() => setSelected(null)} aria-label="Close entity detail">×</button>}><Badge>{picked.status}</Badge><dl className="facts"><div><dt>Identity</dt><dd>{picked.identity}</dd></div><div><dt>Authority</dt><dd>{picked.authority}</dd></div><div><dt>Last observation</dt><dd>{text(picked.seen)} · {age(picked.seen)}</dd></div></dl><ClawInventory row={picked}/><h3>Advertised capabilities</h3><pre>{JSON.stringify(picked.capabilities,null,2)}</pre><p className="muted">Advertisement does not establish authorization or successful execution.</p><button className="primary" onClick={() => investigate(picked.name, picked.raw, '/api/n2n', sources.n2n?.lastSuccess)}>Investigate in canvas ↗</button>{mode === 'advanced' && <details><summary>Source record</summary><pre>{JSON.stringify(picked.raw,null,2)}</pre></details>}</Panel>}</div>}
      {view === 'science' && <><Panel title="Jev Claw · Science Officer" eyebrow="Advisory service"><p>Border retains decision authority. Assessment details belong to their originating task and conversation.</p><div className="metric-grid compact">{['daily_used_usd','daily_limit_usd','case_used_usd','case_limit_usd'].map((k,i) => <div className="mini-metric" key={k}><span>{['UTC daily spend','Daily limit','Task / case spend','Task / case limit'][i]}</span><strong>{money(list(feed.advisors)[0]?.budgets?.[k])}</strong></div>)}</div><Source source={sources.n2n} name="Advisor status snapshot"/>{preview && <button onClick={() => setAssessment({ records: [previewAssessment, { ...previewAssessment, assessment_id: 'synthetic-reconsideration', reconsideration_of: previewAssessment.assessment_id, influence: { status: 'changed', explanation: 'Synthetic Border interpretation after additional interface evidence.' } }] })}>Inspect synthetic original & reconsideration</button>}<AssessmentView {...assessment}/></Panel></>}
      {view === 'network' && <><Panel title="Configured device inventory" eyebrow="Testbed · not observed health"><Source source={sources.graph} name="Local testbed catalogue"/><div className="table-scroll"><table><thead><tr><th>Device</th><th>Platform</th><th>Type</th><th>Investigation</th></tr></thead><tbody>{list(graph.devices).filter(d => JSON.stringify(d).toLowerCase().includes(query)).map((d,i) => <tr key={d.id || i}><td>{text(d.name || d.id)}</td><td>{text(d.os || d.platform)}</td><td>{text(d.type)}</td><td><button onClick={() => investigate(text(d.name), d, 'Configured testbed; verify device state', sources.graph?.lastSuccess)}>Inspect device ↗</button></td></tr>)}</tbody></table>{!list(graph.devices).length && <p className="empty">No configured devices returned. This is not proof of an empty network.</p>}</div></Panel><Panel title="Routing, topology & paths" eyebrow="Observed versus simulated"><button onClick={() => setThree(!three)} disabled={!bgpRows.length}>{three ? 'Hide BGP 3D view' : 'Explore BGP sessions in 3D'}</button>{three && bgpRows.length > 0 && <Suspense fallback={<p>Loading BGP view…</p>}><Scene rows={bgpRows} network onSelect={setSelected}/></Suspense>}<div className="table-scroll"><table><thead><tr><th>BGP peer</th><th>Session state</th><th>Received routes</th><th>Detail</th></tr></thead><tbody>{bgpRows.map(row => <tr key={row.key}><td>{row.name}</td><td><Badge>{row.status}</Badge></td><td>{text(row.raw.routesReceived)}</td><td><button onClick={() => setSelected(row.key)}>Inspect</button></td></tr>)}</tbody></table></div>{pickedBgp && <div className="question"><h3>{pickedBgp.name}</h3><pre>{JSON.stringify(pickedBgp.raw,null,2)}</pre><button onClick={() => investigate(pickedBgp.name,pickedBgp.raw,'/api/bgp',sources.bgp?.lastSuccess)}>Investigate peer ↗</button></div>}<Source source={sources.bgp} name="Local BGP source"/><p>Use a sourced routing or topology snapshot to investigate paths. The Risk relationship graph describes federation, not network cabling.</p><button className="primary" onClick={() => investigate('Routing topology', 'Collect current routing and topology evidence in scope, report snapshot time, and distinguish observed paths from simulation.')}>Investigate routing ↗</button>{mode === 'advanced' && <details><summary>Routing source record</summary><pre>{JSON.stringify(sources.bgp?.payload || { status: 'Unavailable' },null,2)}</pre></details>}</Panel></>}
      {view === 'operations' && <Panel title="Pending approvals & audit" eyebrow="Reported federation workflow"><Source source={sources.n2n} name="Federation approval / GAIT snapshot"/>{list(feed.approvals).length ? list(feed.approvals).map((approval,i) => <div className="attention-row" key={approval.id || i}><div><strong>{text(approval.description || approval.action || approval.id,'Pending approval')}</strong><p>Review through the existing approval workflow. Viewing this panel does not approve it.</p></div><button onClick={() => investigate('Pending approval',approval,'Federation approval snapshot',sources.n2n?.lastSuccess)}>Review ↗</button></div>) : <p>No pending approvals returned in this snapshot. A missing approval feed is not proof that none exist.</p>}<details><summary>Recent GAIT events ({list(feed.gait).length} returned)</summary><pre>{JSON.stringify(list(feed.gait).slice(-50),null,2)}</pre></details></Panel>}
      {['knowledge','operations'].includes(view) && <div className="guide-grid">{GUIDES[view].map(([name,description,prompt,id]) => <Panel key={id} title={name} eyebrow="Scoped investigation"><p>{description}</p><p className="muted">Review through the existing tool workflow. No live metric feed is implied.</p><button className="primary" onClick={() => investigate(name,prompt)}>Investigate in canvas ↗</button>{name === 'RAG collections' && <button className="utility-link" onClick={() => nav('rag')}>Open RAG uploads & retrieval ↗</button>}</Panel>)}</div>}
      {view === 'integrations' && <ClawInventory row={{kind:'local',raw:{inventory:sources.runtime?.payload || {}}}} title="Local Claw · configured MCPs & LLM"/>}
      {view === 'integrations' && <Panel title="Integrations & skills" eyebrow="Capability catalogue"><Source source={sources.graph} name="Repository skill definitions"/><div className="integration-grid">{list(graph.integrations).filter(i => `${i.name} ${i.id} ${i.category} ${i.description} ${list(graph.skills).filter(s => s.integrationId === i.id).map(s => s.id).join(' ')}`.toLowerCase().includes(query)).map(i => <article className="integration" key={i.id}><span className="eyebrow">{i.category}</span><h3>{i.name}</h3><p>{i.description}</p><small>{i.skillCount ?? 'Unknown'} skills · catalogue entry</small><details><summary>Skills & supported actions</summary><ul>{list(graph.skills).filter(s => s.integrationId === i.id).map(s => <li key={s.id}><button onClick={() => investigate(s.id, { skill: s.id, description: s.description }, 'Skill catalogue', sources.graph?.lastSuccess)}>{s.id} ↗</button></li>)}</ul></details><button className="text-button" onClick={() => investigate(i.name, `Review available ${i.name} capabilities and connection/setup state. Verify before reporting operational health.`)}>Investigate →</button></article>)}</div></Panel>}
      {view === 'security' && <SecurityView preview={preview} settings={sources.security?.payload} posture={feed.posture} sourceAvailable={sources.n2n?.state==='available'} onLogs={id => { nav('logs'); setLogSource(id); }} onConfiguration={() => nav('configuration')} onDocs={() => nav('documentation')}/>}
      {view === 'logs' && <LogsView preview={preview} investigate={investigate} initialSource={logSource}/>}
      {view === 'tokenomics' && <TokenomicsView preview={preview} budget={sources.budget} advisors={list(feed.advisors)} rows={rows}/>}
      {view === 'documentation' && <DocumentationView preview={preview}/>}
      {view === 'rag' && <RagView preview={preview} investigate={investigate}/>}
      {view === 'configuration' && <ConfigurationView preview={preview}/>}
      {view === 'settings' && <><Panel title="Runtime & presentation" eyebrow="Local installation"><dl className="facts">{list(graph.settings).map(s => <div key={s.label}><dt>{s.label}</dt><dd>{text(s.value)}</dd></div>)}</dl><p>Basic and Advanced change presentation only. Provider credentials and operational permissions remain in the existing configuration.</p><a className="utility-link" href="/classic.html" target="_blank" rel="noreferrer">Open existing configuration, budgets & utilities ↗</a></Panel><Panel title="Usage & budgets" eyebrow="Recorded scope"><Source source={sources.budget} name="Existing budget estimator"/><p>Latest runtime session estimate; it is not this canvas's task spend or an invoice.</p><div className="answer-grid"><div><span>Estimated latest session cost</span><strong>{money(sources.budget?.payload?.sessionCostUsd)}</strong></div><div><span>Configured session budget</span><strong>{money(sources.budget?.payload?.sessionBudgetUsd)}</strong></div></div><p className="muted">Jev UTC daily and task/case budgets are shown separately in Science Officer.</p></Panel></>}
      <section hidden={view !== 'canvas'} className="canvas-workspace" aria-label="Canvas context and chat workspace">
        {pending && <div className="context-review"><h2>Selected investigation context</h2><pre>{pending}</pre><button className="primary" onClick={sendContext} disabled={!canvasReady}>Add to canvas draft</button><button onClick={() => setPending(null)}>Discard selection</button><p className="muted">Review the draft before sending. This does not run a tool.</p></div>}
        <div className="canvas-toolbar"><span>Canvas · full workspace</span><a href="/canvas.html" target="_blank" rel="noreferrer">Open full canvas in a tab ↗</a></div>
        {preview ? <div className="empty"><h3>Canvas preserved in the application</h3><p>This portable preview contains synthetic dashboard records. Run the local app to use the existing canvas, saved sessions and Border chat.</p></div> : canvasLoaded && <iframe ref={frame} src="/canvas.html?embedded=1" title="Canvas context and chat workspace" onLoad={() => { frame.current?.contentWindow.postMessage({ type: 'netclaw:ready-query' }, location.origin); }}/>} 
      </section>
      <div hidden={!['chat','pal'].includes(view)}><StandardChat preview={preview} active={['chat','pal'].includes(view)} pal={view === 'pal'}/><p className="chat-interface-note">{isHermes ? 'Hermes provides qualified read-only assistance. Attachments, model locks, write execution and federation are unavailable in this release.' : 'Canvas offers branching investigations. OpenClaw opens its native interface in a separate tab with its own sign-in and history. For SSH access, also forward the configured gateway port.'}{!openClawHref && <span> {openClawReason}</span>}</p></div>
      {view === 'pal' && !isHermes && <details className="pal-cloud-option" onToggle={event=>setCloudPalOpen(event.currentTarget.open)}><summary>Optional Tavus video service</summary><p>Uses your own Tavus account and available minutes. This is separate from your local John and Lobster avatars.</p>{cloudPalOpen && <Pal preview={preview} active={view === 'pal' && cloudPalOpen}/>}</details>}
      <footer><span>NETCLAW / FUNCTION FIRST</span><span>{preview ? 'Synthetic preview' : 'Local sources'} · Evidence before conclusions</span></footer>
      </main>
    </div>
  </div>;
}
