import { runtimeInfo } from '../shared/runtime-client.js';
import React, { useEffect, useState } from 'react';
import { age, clawInventory, securitySummary, list, money, text } from './model.js';
import referenceSnapshot from '../../../../docs/reference/interfaces.json';
import documentSnapshot from '../../../../docs/reference/documents.json';
const get = async (url,signal) => { const r=await fetch(url,{cache:'no-store',signal});if(!r.ok)throw Error('Source unavailable');return r.json(); };
const toolName = t => typeof t === 'string' ? t : text(t?.name);
export function ClawInventory({row,title='MCPs & model'}) {
  const inv=clawInventory(row);
  return <section className="panel claw-inventory"><h3>{title}</h3><dl className="facts"><div><dt>Harness</dt><dd>{inv.harness} · {inv.harnessVersion}</dd></div><div><dt>Configured / advertised LLM</dt><dd>{inv.model}</dd></div><div><dt>Model guard</dt><dd>{typeof inv.guarded==='boolean'?inv.guarded?'Reported guarded':'Reported unguarded':'Not reported'}</dd></div></dl>{inv.fallbacks.length > 0 && <p>Configured fallback models: {inv.fallbacks.join(', ')}</p>}<p className="source">{inv.source} · {age(inv.observedAt)}{inv.stale?' · Stale advertisement':''}</p><p className="muted">Configuration and advertisements do not prove reachability or grant tool execution.</p>
    {!inv.available && <p>MCP inventory not reported. Updated agent members report on reconnect; a mobile edge has no local agent runtime.</p>}
    {inv.available && !inv.servers.length && <p>No MCPs reported in this inventory.</p>}
    {inv.servers.map((server,i)=>{const name=typeof server==='string'?server:text(server.name);const tools=list(server.tools);const reference=referenceSnapshot.mcps.find(m=>m.name===name);return <details key={name+':'+i} className="config-item"><summary>{name} · {tools.length?`${tools.length} reported tools`:'tool list not reported'}</summary>{server.transport && <p>Transport: {server.transport}</p>}{tools.map((tool,j)=><details key={toolName(tool)+j}><summary>{toolName(tool)}</summary>{typeof tool==='object'&&tool.description&&<p>{tool.description}</p>}{typeof tool==='object'&&tool.inputSchema?<pre>{JSON.stringify(tool.inputSchema,null,2)}</pre>:<p>Runtime input schema not reported. Consult this server's tools/list before calling.</p>}</details>)}{!tools.length&&<p>The server is listed, but this observation contains no runtime tool manifest.</p>}{reference&&<details><summary>Repository reference · {reference.tools.length} source signatures</summary><p>{reference.coverage}</p>{reference.tools.map((t,j)=><article key={t.name+j} className="question"><strong>{t.name}</strong><pre>{t.signature}</pre><p>{t.description}</p><small>{t.source}:{t.line}</small></article>)}</details>}</details>;})}
  </section>;
}
const demoUsage={available:true,scope:'Synthetic examples; no real billing data.',generatedAt:'2026-09-28T12:00:00Z',records:12,missingUsage:1,malformed:0,skippedFiles:0,groups:[{model:'example/border-model',provider:'Example provider',calls:12,input:42000,output:6200,cacheRead:18000,cacheWrite:4000,costUsd:.08,costRecords:12,incompleteTokenRecords:0}]};
export function TokenomicsView({preview,budget,advisors,rows}) {
  const [usage,setUsage]=useState(preview?demoUsage:null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  useEffect(()=>{if(preview)return;const c=new AbortController();get('/api/hud/tokenomics',c.signal).then(setUsage).catch(()=>{if(!c.signal.aborted)setError('Usage source unavailable');});return()=>c.abort();},[preview,refresh]);
  const groups=list(usage?.groups), sum=k=>groups.reduce((n,g)=>n+(typeof g[k]==='number'?g[k]:0),0);
  const recorded=sum('costRecords'), cost=recorded?sum('costUsd'):null, b=budget?.state==='available'&&budget.payload?.status!=='unknown'?budget.payload:null;
  return <div><section className="panel"><span className="eyebrow">Usage, costs & limits</span><h2>Tokenomics</h2><p>{usage?.scope || 'Reading local recorded usage…'}</p><button disabled={preview} onClick={()=>{setError('');setRefresh(n=>n+1);}}>Refresh token usage</button>{error&&<p role="alert">{error}</p>}{usage?.available===false&&<p role="alert">{usage.error}</p>}<div className="metric-grid compact">{[['Recorded input',usage?.records?sum('input').toLocaleString():'Unknown'],['Recorded output',usage?.records?sum('output').toLocaleString():'Unknown'],['Recorded cost',money(cost)],['Usage records',usage?.records??'Unknown']].map(([k,v])=><div className="mini-metric" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="muted">Recorded provider/runtime cost is not an invoice. Missing token fields are excluded from sums. Cache reads/writes are separate; no unsupported savings estimate is inferred.</p><p>Coverage: {usage?.missingUsage??'Unknown'} assistant messages missing usage · {sum('incompleteTokenRecords')} partial token records · {usage?.skippedFiles??'Unknown'} files excluded · {usage?.malformed??'Unknown'} malformed lines. Cost reported on {recorded} of {usage?.records??'unknown'} usage records.</p></section>
    <section className="panel"><h2>Model usage breakdown</h2><div className="table-scroll"><table><thead><tr>{['Provider / model','Calls','Input','Output','Cache read','Cache write','Recorded USD'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{groups.map(g=><tr key={g.provider+g.model}><td>{g.provider}<small>{g.model}</small></td><td>{g.calls}</td><td>{g.input}</td><td>{g.output}</td><td>{g.cacheRead}</td><td>{g.cacheWrite}</td><td>{money(g.costUsd)}</td></tr>)}</tbody></table></div>{!groups.length&&<p>No recorded usage available; this is not proof of zero spend.</p>}</section>
    <div className="guide-grid"><section className="panel"><h2>Local session budget & estimate</h2><dl className="facts"><div><dt>Configured session ceiling</dt><dd>{money(b?.sessionBudgetUsd)}</dd></div><div><dt>Latest session estimate</dt><dd>{money(b?.sessionCostUsd)}</dd></div><div><dt>Tool calls per turn</dt><dd>{text(b?.maxToolCallsPerTurn)}</dd></div></dl><p>The existing estimator assumes $0.17 per assistant turn in the latest session. It is a heuristic, not model-priced usage and not necessarily this Canvas session. It cannot prove that enforcement halted execution.</p></section><section className="panel"><h2>Jev advisory budgets</h2>{advisors.length?advisors.map((a,i)=><div key={a.advisor_id||i}><strong>{text(a.display_name)}</strong><p>Model: {text(a.model)}</p><p>UTC day: {money(a.budgets?.daily_used_usd)} / {money(a.budgets?.daily_limit_usd)}</p><p>Task/case: {money(a.budgets?.case_used_usd)} / {money(a.budgets?.case_limit_usd)}</p><small>{text(a.case_scope,'Task scope not reported')}</small></div>):<p>Jev budget ledger unavailable or not configured.</p>}<p className="muted">Jev's task/case ledger is separate from gateway session estimates. These totals are not added together.</p></section></div>
    <section className="panel"><h2>Claw model coverage</h2><p>Member and external peer spend is not included unless reported by a supported usage source. No remote usage is inferred from the local gateway.</p><div className="table-scroll"><table><thead><tr><th>Claw</th><th>Reported model</th><th>Usage source</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><td>{r.name}<small>{r.identity}</small></td><td>{clawInventory(r).model}</td><td>{r.kind==='advisor'?'Separate advisory ledger':'Not reported in local usage feed'}</td></tr>)}</tbody></table></div></section>
  </div>;
}
function DocText({content,path,documents,open}) {
  // Render text and allowlisted links as React nodes, never injected HTML.
  const inline=line=>line.split(/(\[[^\]]+\]\([^)]+\))/g).map((part,i)=>{const m=part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);if(!m)return part;let target;try{target=new URL(m[2],'https://local.invalid/'+path);}catch{return part;}if(target.hostname==='local.invalid'){const doc=documents.find(d=>d.path===decodeURIComponent(target.pathname.slice(1)));return doc?<button className="text-button" key={i} onClick={()=>open(doc)}>{m[1]} ↗</button>:part;}return target.protocol==='https:'||target.protocol==='http:'?<a key={i} href={target.href} target="_blank" rel="noreferrer">{m[1]}</a>:part;});
  let code=false;
  return <div className="document-content">{content.split('\n').map((line,i)=>{if(line.startsWith('```')){code=!code;return null;}if(code)return <pre key={i}>{line||' '}</pre>;const heading=line.match(/^(#{1,6}) (.+)/);return heading?React.createElement('h'+Math.min(heading[1].length+1,6),{key:i},heading[2]):<p key={i}>{inline(line)||' '}</p>;})}</div>;
}
export function DocumentationView({preview}) {
  const [documents,setDocuments]=useState(preview?documentSnapshot:[]),[reference,setReference]=useState(preview?referenceSnapshot:null),[tab,setTab]=useState('guides'),[query,setQuery]=useState(''),[doc,setDoc]=useState(null),[error,setError]=useState('');
  useEffect(()=>{if(preview)return;const c=new AbortController();Promise.all([get('/api/hud/documentation',c.signal),get('/api/hud/reference',c.signal)]).then(([d,r])=>{setDocuments(d.documents);setReference(r);}).catch(()=>{if(!c.signal.aborted)setError('Documentation index unavailable');});return()=>c.abort();},[preview]);
  const open=async item=>{setError('');if(preview){setDoc({...item,content:globalThis.NETCLAW_PREVIEW_DOCUMENTS?.[item.path]||`# ${item.title}\nSource: ${item.path}\nOpen this guide in the running application or repository. This portable preview includes selected guides only.`});return;}try{setDoc(await get('/api/hud/documentation/'+item.id,AbortSignal.timeout(15000)));}catch{setError('Document could not be read');}};
  const q=query.toLowerCase(), matches=value=>JSON.stringify(value).toLowerCase().includes(q);
  return <section className="panel workspace-tools"><span className="eyebrow">Read, explore, verify</span><h2>Documentation & reference</h2><article className="community-guide"><span className="eyebrow">Community perspective</span><h3>Sean Mahoney’s NetClaw technical guide</h3><p>A 12-section guide covering architecture, skills, MCPs, federation, security and token optimization. Published July 22, 2026; use this repository for current commands and counts.</p><a href="https://www.seanmahoney.ai/guides/netclaw-overview/" target="_blank" rel="noreferrer">Read Sean’s guide ↗</a></article><p>README, operator guides, skill procedures, CLI options and source-derived interfaces in one place. Browsing this area executes no commands.</p><div className="tab-actions">{[['guides','Guides'],['cli','CLI reference'],['mcps','MCP reference'],['http','HTTP API'],['modalities','Modalities']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setDoc(null);}}>{label}</button>)}</div><label className="tool-form">Search documentation & interfaces<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Command, flag, MCP, API path or guide…"/></label>{error&&<p role="alert">{error}</p>}
    {doc?<article><button onClick={()=>setDoc(null)}>← Back to reference</button><p className="source">{doc.path}</p><DocText {...doc} documents={documents} open={open}/></article>:<>
    {tab==='guides'&&<div className="integration-grid">{documents.filter(matches).map(d=><article className="integration" key={d.id}><span className="eyebrow">{d.category}</span><h3>{d.title}</h3><small>{d.path}</small><button onClick={()=>open(d)}>Read guide ↗</button></article>)}</div>}
    {tab==='cli'&&<><p>{reference?.scope}</p><p>{list(reference?.cli).length} source entries. Flags mentioned in source may belong to delegated commands; read their declaration context. Full upstream CLI help depends on the installed version.</p>{list(reference?.cli).filter(matches).map(c=><details key={c.path} className="config-item"><summary>{c.path} · {c.flags.length} flags mentioned</summary><p>{c.coverage}</p><p>{c.flags.join(' · ')||'No long flags found'}</p>{c.declarations.map((d,i)=><pre key={i}>L{d.line}: {d.declaration}</pre>)}{!c.declarations.length&&<p>No static argument declarations; consult the script's entry point.</p>}</details>)}</>}
    {tab==='mcps'&&<><p>Repository registrations and source signatures. Actual Claw observations are shown in their inspectors. MCP uses JSON-RPC tools/list and tools/call; this reference does not manufacture REST endpoints.</p>{list(reference?.mcps).filter(matches).map(m=><details className="config-item" key={m.name}><summary>{m.name} · {m.transport} · {m.tools.length} source signatures</summary><p>{m.coverage}</p>{m.tools.map((t,i)=><article className="question" key={t.name+i}><h3>{t.name}</h3><pre>{t.signature}</pre><p>{t.description}</p><small>{t.source}:{t.line}</small></article>)}</details>)}</>}
    {tab==='http'&&<><p>HUD OpenAPI 3.1 route inventory. Generic request/response schemas remain unspecified; source locations identify the implementation. Mutating routes require the existing local guards and workflow rules.</p>{!preview&&<a href="/api/hud/openapi.json" target="_blank" rel="noreferrer">Open / save OpenAPI JSON ↗</a>}{Object.entries(reference?.http?.paths||{}).flatMap(([path,methods])=>Object.entries(methods).map(([method,op])=>({path,method,op}))).filter(matches).map(r=><details key={r.method+r.path} className="config-item"><summary>{r.method.toUpperCase()} {r.path}</summary><p>{r.op.description}</p><pre>{JSON.stringify(r.op,null,2)}</pre></details>)}<details className="config-item"><summary>Federation daemon route reference</summary><p>{reference?.daemon?.source} · source conditions, including dynamic routes; not a complete OpenAPI schema.</p>{list(reference?.daemon?.conditions).map((d,i)=><pre key={i}>L{d.line}: {d.declaration}</pre>)}</details></>}
    {tab==='modalities'&&<div className="guide-grid">{[['Canvas & HUD','Branching conversations, attachments, four answer tabs, evidence panels and optional Three.js views.'],['Terminal & TUI','scripts/netclaw menu, direct commands and installer; OpenClaw or Hermes runtime selected by NETCLAW_RUNTIME.'],['Chat channels','Slack and WebEx use configured channel integrations; permissions and change gates still apply.'],['Mobile','Text, voice, camera/microphone capture, QR/deep links, notifications and biometric approval. Border or a delegated member supplies the LLM.'],['MCP & HTTP','MCP stdio/HTTP tool interfaces, local HUD REST routes and authenticated federation RPC.'],['Federation','iN2N internal members and eN2N external neighbours retain separate scope, consent, budgets and evidence provenance.']].map(([name,body])=><article className="integration" key={name}><h3>{name}</h3><p>{body}</p></article>)}</div>}
    </>}
  </section>;
}

const previewLogSources=[{id:'defenseclaw',name:'DefenseClaw',kind:'file',command:'tail -n 200 ~/.defenseclaw/gateway.log'},{id:'openshell-build',name:'OpenShell sandbox build',kind:'file',command:'tail -n 200 /tmp/sandbox-build.log'},{id:'mesh',name:'BGP / federation',kind:'file',command:'tail -n 200 /tmp/bgp-daemon-v2.log'},{id:'gateway-journal',name:'Gateway journal',kind:'journal',command:'journalctl --user -u openclaw-gateway.service -n 200 --no-pager'}];
const previewLogRows=[{id:1,severity:'info',timestamp:'2026-09-28T12:00:00Z',message:'SYNTHETIC INFO federation inventory refreshed'},{id:2,severity:'warning',timestamp:'2026-09-28T12:00:02Z',message:'SYNTHETIC WARNING member heartbeat delayed; current device health unknown'}];
export function LogsView({preview,investigate,initialSource='mesh'}) {
  const [sources,setSources]=useState(preview?previewLogSources:[]),[source,setSource]=useState(initialSource),[query,setQuery]=useState(''),[severity,setSeverity]=useState('all'),[live,setLive]=useState(false),[refresh,setRefresh]=useState(0),[data,setData]=useState(null),[error,setError]=useState(''),[copied,setCopied]=useState('');
  useEffect(()=>{if(preview)return;const c=new AbortController();get('/api/hud/logs',c.signal).then(d=>setSources(d.sources)).catch(()=>{if(!c.signal.aborted)setError('Log source catalogue unavailable');});return()=>c.abort();},[preview]);
  useEffect(()=>{if(preview){setData({rows:previewLogRows.filter(r=>(severity==='all'||r.severity===severity)&&r.message.toLowerCase().includes(query.toLowerCase())),readAt:'2026-09-28T12:00:03Z',scope:'Synthetic log preview'});return;}const c=new AbortController();let timer;setData(null);setError('');const read=async()=>{try{const result=await get(`/api/hud/logs/${encodeURIComponent(source)}?q=${encodeURIComponent(query)}&severity=${severity}`,AbortSignal.any([c.signal,AbortSignal.timeout(10000)]));if(!c.signal.aborted){setData(result);setError('');}}catch{if(!c.signal.aborted)setError('Log unavailable or read failed. Previously loaded lines may be stale. Check the service command below.');}if(live&&!c.signal.aborted)timer=setTimeout(read,5000);};const debounce=setTimeout(read,200);return()=>{c.abort();clearTimeout(timer);clearTimeout(debounce);};},[preview,source,query,severity,live,refresh]);
  const selected=sources.find(s=>s.id===source),rows=list(data?.rows);
  return <div className="workspace-tools"><section className="panel"><span className="eyebrow">Observe & investigate</span><h2>Service logs</h2><p>Read a bounded service tail, filter locally sourced evidence, and carry selected lines into Canvas. No remote syslog collector is started.</p><div className="log-controls tool-form"><label>Service<select value={source} onChange={e=>setSource(e.target.value)}>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}>{['all','error','warning','info','debug','unknown'].map(s=><option key={s}>{s}</option>)}</select></label><label>Contains<input value={query} maxLength={200} onChange={e=>setQuery(e.target.value)} placeholder="Literal text, identity or event…"/></label></div><div className="tab-actions"><button onClick={()=>setRefresh(n=>n+1)} disabled={preview}>Refresh logs</button><button aria-pressed={live} onClick={()=>setLive(!live)} disabled={preview}>{live?'Pause auto-refresh':'Auto-refresh every 5s'}</button></div>{error&&<p role="alert">{error}</p>}<p className="source">{data?.scope} · {data?.readAt?`Read ${age(data.readAt)}`:'No successful read'}{data?.truncated?' · Tail limited':''}</p><p className="muted">Severity is parsed or inferred. Known credential patterns are redacted; logs may still contain operational details. Filters apply only to the bounded tail.</p>
    <div className="table-scroll"><table><thead><tr><th>Time / severity</th><th>Message</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.timestamp||'Time unknown'}<small>{r.severity}</small></td><td><pre>{r.message}</pre></td><td><button onClick={()=>investigate('Service log evidence',{service:source,...r},'/api/hud/logs/'+source,data?.readAt)}>Investigate ↗</button></td></tr>)}</tbody></table></div>{data&&!rows.length&&<p>No matching lines in this tail. This is not proof that no events occurred.</p>}</section>
    <section className="panel"><h2>Logging commands</h2><p>Copy and run in your terminal when needed. The HUD does not execute pasted commands.</p><pre>{selected?.command||'Select a service'}</pre><button onClick={async()=>{try{await navigator.clipboard.writeText(selected.command);setCopied('Command copied');}catch{setCopied('Select and copy the command above');}}} disabled={!selected}>Copy logging command</button>{copied&&<p role="status">{copied}</p>}<p>For Linux service follow/filter commands and device syslog workflows, open <strong>Documentation → Guides → Logging and troubleshooting</strong>. Search the CLI reference for journalctl, logs, heartbeat, peering or syslog.</p><button onClick={()=>investigate('Syslog investigation','Review the available syslog receiver, Loki, Elasticsearch or other configured log sources. Establish collector, time range and scope before searching; cite timestamps and do not start or reconfigure a collector.')}>Investigate collected syslog in Canvas ↗</button></section>
  </div>;
}

export function SecurityOverview({settings,posture,sourceAvailable,onOpen}) {
  if(runtimeInfo()?.kind==='hermes')return <section className="panel security-summary"><h2>Hermes · Qualified read-only execution</h2><p>Only reviewed tool implementations and argument scopes can execute. Writes, shell, delegation and shared memory are unavailable.</p><button onClick={onOpen}>Inspect Security ↗</button></section>;
  const summary=securitySummary(settings,posture,sourceAvailable);
  return <section className="panel security-summary"><div><span className="eyebrow">Operating mode & protection</span><h2>{summary.label}</h2><p><strong>{summary.lab}</strong> · Configured federation mode: {text(settings?.riskMode,'Unknown')} · DefenseClaw: {text(settings?.defenseMode,'Unknown')}</p><p className="muted">LAB change-gate bypass, federation mode, model guard, and sandbox enforcement are distinct controls.</p></div><button onClick={onOpen}>Inspect Security ↗</button></section>;
}
export function SecurityView({preview,settings,posture,sourceAvailable,onLogs,onConfiguration,onDocs}) {
  const [shell,setShell]=useState(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  useEffect(()=>{if(runtimeInfo()?.kind==='hermes')return;if(preview){setShell({commands:[{command:'openshell gateway status',available:false,output:'Synthetic preview: OpenShell not probed'},{command:'openshell sandbox list',available:false,output:'Synthetic preview: no container state claimed'}]});return;}const c=new AbortController();get('/api/hud/openshell',AbortSignal.any([c.signal,AbortSignal.timeout(12000)])).then(setShell).catch(()=>{if(!c.signal.aborted)setError('OpenShell status unavailable');});return()=>c.abort();},[preview,refresh]);
  if(runtimeInfo()?.kind==='hermes')return <section className="panel"><h2>Hermes execution policy</h2><p>The pinned companion disables shared memory and unrestricted tools. Source drift or schema changes block execution. Production and Local/Lab APPLY are unavailable.</p><p>Readiness and actual tool execution are reported separately. A running API is not proof that a tool succeeded.</p><button onClick={onConfiguration}>Configuration items ↗</button></section>;
  const summary=securitySummary(settings,posture,sourceAvailable),controls=list(posture?.controls),guard=controls.find(c=>c.name==='model-guard'),sandbox=controls.find(c=>c.name==='sandbox');
  const state=c=>!summary.fresh?'Unknown / stale':c?.available===true?'Available in last probe':c?.available===false?'Unavailable in last probe':'Not reported';
  return <div className="workspace-tools"><section className="panel"><span className="eyebrow">LAB / PRODUCTION</span><h2>{summary.label}</h2><p>{summary.lab}</p><p>Configured federation mode: <strong>{text(settings?.riskMode,'Unknown')}</strong> · Runtime reported mode: <strong>{text(posture?.mode,'Unknown')}</strong> · Probed {age(posture?.computed_at)}</p><p className="source">{settings?.source || 'Settings not available'}</p><p>NETCLAW_LAB_MODE can relax supported ServiceNow change checks. N2N_RISK_MODE controls federation preflight enforcement. Neither flag alone proves that DefenseClaw or confinement is active.</p><div className="tab-actions"><button onClick={onConfiguration}>Configuration items ↗</button><button onClick={onDocs}>Security setup guides ↗</button></div></section>
    <div className="guide-grid"><section className="panel"><span className="eyebrow">Model guard</span><h2>DefenseClaw</h2><h3>{state(guard)}</h3><p>{text(guard?.detail,'No guard probe detail reported')}</p><dl className="facts"><div><dt>Security mode</dt><dd>{text(settings?.defenseMode,'Unknown')}</dd></div><div><dt>Guardrail mode</dt><dd>{text(settings?.guardMode,'Unknown')}</dd></div><div><dt>Configured guard port</dt><dd>{text(settings?.guardPort,'Unknown')}</dd></div><div><dt>Reported model route</dt><dd>{text(posture?.model?.primary,'Not reported')}</dd></div></dl><p>Observe mode records findings; it is not equivalent to blocking. A configured model route or installed CLI does not prove the guard is reachable.</p><p>Security mode file: <code>~/.openclaw/config/openclaw.json</code>. Guard settings: <code>~/.defenseclaw/config.yaml</code>.</p><pre>defenseclaw alerts</pre><button onClick={()=>onLogs('defenseclaw')}>DefenseClaw logs ↗</button></section>
    <section className="panel"><span className="eyebrow">Optional container path</span><h2>OpenShell</h2><p>OpenShell container status is separate from the host-level iN2N member-confinement probe. A listed sandbox does not establish that a specific agent is running inside it.</p><button disabled={preview} onClick={()=>{setError('');setRefresh(n=>n+1);}}>Refresh OpenShell status</button>{error&&<p role="alert">{error}</p>}{!shell&&<p>Reading fixed status commands…</p>}{list(shell?.commands).map(c=><details key={c.command} open><summary>{c.command} · {c.available?'Command completed':'Unavailable / not verified'}</summary><pre>{c.output}</pre></details>)}<p className="muted">Read-only status probes, cached for 30 seconds. No sandbox is created or reconfigured.</p><pre>./scripts/netclaw-secure-start.sh status</pre><p>Launcher policy: <code>/tmp/netclaw-sandbox-policy.yaml</code>. Generated policy and credentials remain local; inspect the launcher guide before changes.</p><button onClick={()=>onLogs('openshell-build')}>OpenShell build logs ↗</button></section></div>
    <section className="panel"><h2>Member confinement & audit</h2><p>Current iN2N member confinement uses systemd user-service restrictions. OpenShell is not required for this specific production-control probe.</p><div className="table-scroll"><table><thead><tr><th>Control</th><th>Observed state</th><th>Detail</th></tr></thead><tbody>{['sandbox','model-guard','audit'].map(name=>{const c=controls.find(c=>c.name===name);return <tr key={name}><td>{name==='sandbox'?'Host member confinement':name==='model-guard'?'DefenseClaw model guard':'GAIT audit'}</td><td>{state(c)}</td><td>{text(c?.detail,'Not reported')}</td></tr>;})}</tbody></table></div><p>Strict-all configured: {settings?.strictAll===true?'Yes':settings?.strictAll===false?'No':'Unknown'}. Missing containment blocks production delegation; audit-only gaps warn unless strict-all applies.</p><pre>python3 scripts/in2n-services.py status</pre><button onClick={()=>onLogs('mesh-journal')}>Federation service logs ↗</button></section>
    <section className="panel"><h2>Mode settings & setup</h2><p>Review current settings in Configuration and follow <strong>Documentation → Security modes, DefenseClaw and OpenShell</strong>. These controls report and explain configuration; viewing this page never switches mode.</p><div className="table-scroll"><table><thead><tr><th>Setting</th><th>Purpose</th><th>Configured</th></tr></thead><tbody><tr><td>NETCLAW_LAB_MODE</td><td>Supported ITSM lab bypass</td><td>{settings?.labMode===true?'true':settings?.labMode===false?'false':'Unknown'}</td></tr><tr><td>N2N_RISK_MODE</td><td>testing / production federation policy</td><td>{text(settings?.riskMode,'Unknown')}</td></tr><tr><td>N2N_STRICT_ALL</td><td>Also block on missing audit</td><td>{settings?.strictAll===true?'true':settings?.strictAll===false?'false':'Unknown'}</td></tr></tbody></table></div><p>DefenseClaw's security.mode belongs in its nested configuration file, not the gateway's root configuration. Verify the running daemon's probes after any operator change.</p><button onClick={onDocs}>Open Documentation ↗</button></section>
  </div>;
}
